-- trial

-- 권한이 'ROLE_STUDENT’을 가진 목록 : AUTHORITY_MEMBER, AUTHORITY 

-- select*from AUTHORITY_MEMBER 
-- INNER JOIN AUTHORITY 
-- ON AUTHORITY_MEMBER.AUTHORITY_ID=AUTHORITY.AUTHORITY_ID 
-- WHERE AUTHORITY.AUTHORITY_ID  like 'ROLE_STUDENT';


-- '강의/강연 신' 조직 구조 확인 : ORGANIZATION, ORGANIZATION_FACILITY

-- SELECT*FROM AUTHORITY ;

-- select*from ORGANIZATION;
-- select*from COOPERATION;

-- SELECT ORGANIZATION.NAME, 
--         PARENT_ORGANIZATION_SEQ, 
--         ORGANIZATION.TYPE,
--         ORGANIZATION.ORGANIZATION_SEQ 
-- FROM ORGANIZATION

-- where PARENT_ORGANIZATION_SEQ is null
-- and ORGANIZATION.NAME LIKE '강의/강연 신';

-- JOIN COOPERATION
-- ON ORGANIZATION.ORGANIZATION_SEQ=COOPERATION.ORGANIZATION_SEQ 



-- 이름이 'yojulab admin'인 회원 소속, 기관, 권한 종류 확인 :
-- SELECT*FROM ORGANIZATION_MEMBER;
-- SELECT*FROM AUTHORITY_MEMBER;
-- SELECT*FROM MEMBER;


-- SELECT MEMBER.MEMBER_SEQ, MEMBER.NAME, AUTHORITY_ID, ORGANIZATION_MEMBER.TYPE
-- FROM MEMBER 

-- INNER JOIN AUTHORITY_MEMBER
-- ON MEMBER.MEMBER_SEQ=AUTHORITY_MEMBER.MEMBER_SEQ and MEMBER.NAME LIKE 'yojulab Admin'
-- INNER JOIN ORGANIZATION_MEMBER
-- ON MEMBER.MEMBER_SEQ=ORGANIZATION_MEMBER.MEMBER_SEQ and MEMBER.NAME LIKE 'yojulab Admin';
