
-- 권한이 'ROLE_STUDENT'을 가진 목록 : AUTHORITY_MEMBER
-- 1

SELECT M.MEMBER_SEQ,M.MEMBER_ID,M.CRYPT_PASSWORD,M.JOB,M.PHONE_NUMBER,M.REGISTRY_DATE,T1.NAME,M.YN
FROM (SELECT M1.MEMBER_SEQ,M1.MEMBER_ID,M1.CRYPT_PASSWORD,M1.NAME AS JOB,M1.PHONE_NUMBER,M1.REGISTRY_DATE,CC.NAME AS YN
      FROM MEMBER AS M1 LEFT OUTER JOIN COMMONCODE AS CC 
      ON M1.TEMPORARY_YN = CC.COMMONCODE_ID) AS M INNER JOIN 
     (SELECT AM.MEMBER_SEQ,AO.NAME
      FROM AUTHORITY AS AO INNER JOIN AUTHORITY_MEMBER AS AM 
      ON AM.AUTHORITY_ID = 'ROLE_STUDENT' AND AO.AUTHORITY_ID ='ROLE_STUDENT') AS T1
ON M.MEMBER_SEQ = T1.MEMBER_SEQ;


-- ORGANIZATION_SEQ ,PARENT_ORGANIZATION_SEQ
--2

WITH RECURSIVE tmp1 AS (
    SELECT ORGANIZATION_SEQ,NAME,PARENT_ORGANIZATION_SEQ
    FROM ORGANIZATION WHERE ORGANIZATION_SEQ ='UUID-ORGANIZATION-YOJULAB'
    UNION ALL
    SELECT o.ORGANIZATION_SEQ,o.NAME,o.PARENT_ORGANIZATION_SEQ
    FROM tmp1 AS t JOIN ORGANIZATION AS o ON o.PARENT_ORGANIZATION_SEQ = t.ORGANIZATION_SEQ
)
SELECT ORGANIZATION_SEQ,NAME,PARENT_ORGANIZATION_SEQ
FROM tmp1;

