-- <QUESTION 1> SEARCH MEMBERS WHOSE AUTHORITY IS ROLE_STUDENT

-- SECOND TRY (200512)
SELECT MEMBER_ID, MEMBER.NAME, REGISTRY_DATE, AUTHORITY.NAME AS ROLE, ORGANIZATION.NAME AS ORG, COMMONCODE.NAME AS TEMP_YN
FROM AUTHORITY INNER JOIN AUTHORITY_MEMBER
    ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
        AND AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT"
    INNER JOIN MEMBER
    ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
        INNER JOIN ORGANIZATION_MEMBER
        ON MEMBER.MEMBER_SEQ = ORGANIZATION_MEMBER.MEMBER_SEQ
            INNER JOIN ORGANIZATION
            ON ORGANIZATION_MEMBER.ORGANIZATION_SEQ = ORGANIZATION.ORGANIZATION_SEQ
                INNER JOIN COMMONCODE
                ON COMMONCODE.COMMONCODE_ID = MEMBER.TEMPORARY_YN;

-- FIRST TRY (200511)
-- SHOULD USE ALIAS WHEN THE COLUMN NAMES ARE SAME IN SELECT PHRASE
-- SELECT MEMBER_ID, MEMBER.NAME, REGISTRY_DATE, AUTHORITY.NAME AS ROLE
-- FROM MEMBER INNER JOIN AUTHORITY_MEMBER
--     ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
--     LEFT OUTER JOIN AUTHORITY
--     ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
-- WHERE AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT";


-- <QUESTION 2> SEARCH ORGANIZATION STURUCTURE OF "강의/강연 신"

-- PATH RESULT IS NOT CORRECT
WITH RECURSIVE TMP1 AS (
    SELECT ORGANIZATION_SEQ, NAME, TYPE, 1 AS LEVEL, PARENT_ORGANIZATION_SEQ
    FROM ORGANIZATION
    WHERE ORGANIZATION_SEQ="UUID-ORGANIZATION-YOJULAB"
    UNION ALL
    SELECT O.ORGANIZATION_SEQ, O.NAME, O.TYPE, T.LEVEL+1 AS LEVEL, O.PARENT_ORGANIZATION_SEQ
    FROM TMP1 AS T JOIN ORGANIZATION AS O ON T.ORGANIZATION_SEQ = O.PARENT_ORGANIZATION_SEQ
)
SELECT ORGANIZATION_SEQ, NAME, TYPE, LEVEL, PARENT_ORGANIZATION_SEQ
FROM TMP1
ORDER BY LEVEL;


-- <QUESTION 3> SEARCH ORGANIZATION, AUTHORITY, BELONG_ORG OF "yojulab admin"

SELECT MEMBER.NAME, ORGANIZATION.NAME AS ORG, AUTHORITY.NAME AS AUTH,
CASE
WHEN ORGANIZATION.PARENT_ORGANIZATION_SEQ IS NULL THEN ORGANIZATION.NAME
WHEN ORGANIZATION.PARENT_ORGANIZATION_SEQ IS NOT NULL THEN PARENT.NAME
END AS PARENT_ORG
FROM AUTHORITY INNER JOIN AUTHORITY_MEMBER
ON AUTHORITY.AUTHORITY_ID = AUTHORITY_MEMBER.AUTHORITY_ID
    INNER JOIN ORGANIZATION_MEMBER
    ON AUTHORITY_MEMBER.MEMBER_SEQ = ORGANIZATION_MEMBER.MEMBER_SEQ
        INNER JOIN ORGANIZATION
        ON ORGANIZATION_MEMBER.ORGANIZATION_SEQ = ORGANIZATION.ORGANIZATION_SEQ
            LEFT OUTER JOIN ORGANIZATION AS PARENT
            ON PARENT.ORGANIZATION_SEQ = ORGANIZATION.PARENT_ORGANIZATION_SEQ
                INNER JOIN MEMBER
                ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
                AND MEMBER.NAME LIKE "yojulab%Admin";

