
-- ORGANIZATION_SEQ
-- PARENT_ORGANIZATION_SEQ

WITH RECURSIVE tmp1 AS (
    SELECT ORGANIZATION_SEQ,NAME,PARENT_ORGANIZATION_SEQ
    FROM ORGANIZATION WHERE ORGANIZATION_SEQ ='UUID-ORGANIZATION-YOJULAB'
    UNION ALL
    SELECT o.ORGANIZATION_SEQ,o.NAME,o.PARENT_ORGANIZATION_SEQ
    FROM tmp1 AS t JOIN ORGANIZATION AS o ON o.PARENT_ORGANIZATION_SEQ = t.ORGANIZATION_SEQ
)
SELECT ORGANIZATION_SEQ,NAME,PARENT_ORGANIZATION_SEQ
FROM tmp1;