
-- SEARCH ORGANIZATION STURUCTURE OF "강의/강연 신"


-- PATH RESULT IS NOT CORRECT
WITH RECURSIVE TMP1 AS (
    SELECT ORGANIZATION_SEQ, NAME, TYPE, 1 AS LEVEL, PARENT_ORGANIZATION_SEQ
    FROM ORGANIZATION
    WHERE ORGANIZATION_SEQ="UUID-ORGANIZATION-YOJULAB"
    UNION ALL
    SELECT O.ORGANIZATION_SEQ, O.NAME, O.TYPE, T.LEVEL+1 AS LEVEL, O.PARENT_ORGANIZATION_SEQ
    FROM TMP1 AS T JOIN ORGANIZATION AS O ON T.ORGANIZATION_SEQ = O.PARENT_ORGANIZATION_SEQ
)
SELECT ORGANIZATION_SEQ, NAME, TYPE, LEVEL, PARENT_ORGANIZATION_SEQ
FROM TMP1
ORDER BY LEVEL;

