-- 1
SELECT MEMBER.MEMBER_SEQ, MEMBER.MEMBER_ID, MEMBER.NAME, AUTHORITY_MEMBER.AUTHORITY_ID 
FROM MEMBER INNER JOIN AUTHORITY_MEMBER ON AUTHORITY_MEMBER.MEMBER_SEQ=MEMBER.MEMBER_SEQ
    INNER JOIN AUTHORITY ON AUTHORITY_MEMBER.AUTHORITY_ID=AUTHORITY.AUTHORITY_ID
    WHERE AUTHORITY.AUTHORITY_ID='ROLE_STUDENT'

-- 2
SELECT * FROM ORGANIZATION

WITH RECURSIVE TEMP AS(
    SELECT ORGANIZATION_SEQ, NAME, TYPE, PARENT_ORGANIZATION_SEQ 
    FROM ORGANIZATION WHERE PARENT_ORGANIZATION_SEQ is NULL

UNION ALL
SELECT O.ORGANIZATION_SEQ, O.NAME, O.TYPE, O.PARENT_ORGANIZATION_SEQ FROM ORGANIZATION O 
INNER JOIN TEMP ON TEMP.ORGANIZATION_SEQ = O.PARENT_ORGANIZATION_SEQ)

SELECT ORGANIZATION_SEQ, NAME, TYPE, PARENT_ORGANIZATION_SEQ FROM TEMP

--3
SELECT * FROM ORGANIZATION_MEMBER;
SELECT * FROM AUTHORITY_MEMBER;

SELECT ORGANIZATION.NAME, ORGANIZATION_MEMBER.TYPE, AUTHORITY_MEMBER.AUTHORITY_ID 
FROM  ORGANIZATION INNER JOIN ORGANIZATION_MEMBER 
ON ORGANIZATION.ORGANIZATION_SEQ=ORGANIZATION_MEMBER.ORGANIZATION_SEQ
INNER JOIN MEMBER ON MEMBER.MEMBER_SEQ=ORGANIZATION_MEMBER.MEMBER_SEQ
INNER JOIN AUTHORITY_MEMBER ON AUTHORITY_MEMBER.MEMBER_SEQ=MEMBER.MEMBER_SEQ


