-- SEARCH MEMBERS WHOSE AUTHORITY IS ROLE_STUDENT

-- SHOULD USE ALIAS WHEN THE COLUMN NAMES ARE SAME IN SELECT PHRASE
SELECT MEMBER_ID, MEMBER.NAME, REGISTRY_DATE, AUTHORITY.NAME AS ROLE
FROM MEMBER INNER JOIN AUTHORITY_MEMBER
    ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
    LEFT OUTER JOIN AUTHORITY
    ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
WHERE AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT";
