
SELECT AUTHORITY_MEMBER.MEMBER_SEQ, AUTHORITY_MEMBER.AUTHORITY_ID, MEMBER.MEMBER_ID, AUTHORITY.NAME
FROM MEMBER INNER JOIN AUTHORITY_MEMBER
    ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
        INNER JOIN AUTHORITY
            ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
WHERE AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT";