
-- 권한이 'ROLE_STUDENT'을 가진 목록 : AUTHORITY_MEMBER


SELECT M.MEMBER_SEQ,M.MEMBER_ID,M.CRYPT_PASSWORD,M.JOB,M.PHONE_NUMBER,M.REGISTRY_DATE,T1.NAME,M.YN
FROM (SELECT M1.MEMBER_SEQ,M1.MEMBER_ID,M1.CRYPT_PASSWORD,M1.NAME AS JOB,M1.PHONE_NUMBER,M1.REGISTRY_DATE,CC.NAME AS YN
      FROM MEMBER AS M1 LEFT OUTER JOIN COMMONCODE AS CC 
      ON M1.TEMPORARY_YN = CC.COMMONCODE_ID) AS M INNER JOIN 
     (SELECT AM.MEMBER_SEQ,AO.NAME
      FROM AUTHORITY AS AO INNER JOIN AUTHORITY_MEMBER AS AM 
      ON AM.AUTHORITY_ID = 'ROLE_STUDENT' AND AO.AUTHORITY_ID ='ROLE_STUDENT') AS T1
ON M.MEMBER_SEQ = T1.MEMBER_SEQ;


