SELECT MEMBER.MEMBER_SEQ, MEMBER.MEMBER_ID, MEMBER.NAME, AUTHORITY_MEMBER.AUTHORITY_ID 
FROM MEMBER INNER JOIN AUTHORITY_MEMBER ON AUTHORITY_MEMBER.MEMBER_SEQ=MEMBER.MEMBER_SEQ
    INNER JOIN AUTHORITY ON AUTHORITY_MEMBER.AUTHORITY_ID=AUTHORITY.AUTHORITY_ID
    WHERE AUTHORITY.AUTHORITY_ID='ROLE_STUDENT'
