-- SEARCH MEMBERS WHOSE AUTHORITY IS ROLE_STUDENT


-- FIRST TRY (200511)
-- SHOULD USE ALIAS WHEN THE COLUMN NAMES ARE SAME IN SELECT PHRASE
-- SELECT MEMBER_ID, MEMBER.NAME, REGISTRY_DATE, AUTHORITY.NAME AS ROLE
-- FROM MEMBER INNER JOIN AUTHORITY_MEMBER
--     ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
--     LEFT OUTER JOIN AUTHORITY
--     ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
-- WHERE AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT";


-- SECOND TRY (200512)
SELECT MEMBER_ID, MEMBER.NAME, REGISTRY_DATE, AUTHORITY.NAME AS ROLE, ORGANIZATION.NAME AS ORG, COMMONCODE.NAME AS TEMP_YN
FROM AUTHORITY INNER JOIN AUTHORITY_MEMBER
    ON AUTHORITY_MEMBER.AUTHORITY_ID = AUTHORITY.AUTHORITY_ID
        AND AUTHORITY.AUTHORITY_ID = "ROLE_STUDENT"
    INNER JOIN MEMBER
    ON MEMBER.MEMBER_SEQ = AUTHORITY_MEMBER.MEMBER_SEQ
        INNER JOIN ORGANIZATION_MEMBER
        ON MEMBER.MEMBER_SEQ = ORGANIZATION_MEMBER.MEMBER_SEQ
            INNER JOIN ORGANIZATION
            ON ORGANIZATION_MEMBER.ORGANIZATION_SEQ = ORGANIZATION.ORGANIZATION_SEQ
                INNER JOIN COMMONCODE
                ON COMMONCODE.COMMONCODE_ID = MEMBER.TEMPORARY_YN;
