-- 권한이 ROLE_STUDENT를 가진 목록
SELECT MEMBER_ID, NAME, PHONE_NUMBER,REGISTRY_DATE, AUTHORITY_ID FROM MEMBER
INNER JOIN AUTHORITY_MEMBER
ON AUTHORITY_MEMBER.MEMBER_SEQ = MEMBER.MEMBER_SEQ
WHERE AUTHORITY_MEMBER.AUTHORITY_ID = 'ROLE_STUDENT';