
-- 권한이 'ROLE_STUDENT'을 가진 목록 : AUTHORITY_MEMBER

SELECT M.*,T1.NAME
FROM MEMBER AS M INNER JOIN (
    SELECT AM.MEMBER_SEQ,AO.NAME
    FROM AUTHORITY_MEMBER AS AM INNER JOIN AUTHORITY AS AO
    ON AM.AUTHORITY_ID = 'ROLE_STUDENT' AND AO.AUTHORITY_ID ='ROLE_STUDENT'
) AS T1
ON M.MEMBER_SEQ = T1.MEMBER_SEQ;
