/* Create Tables */

-- 대상자 답변
CREATE TABLE ANSWER
(
	-- 대상자 답변 SEQ
	ANSWER_SEQ varchar(40) NOT NULL COMMENT '대상자 답변 SEQ',
	-- 해답 및 답변(객관식/짧은 주관식) or 응답
	ANSWER varchar(2000) COMMENT '해답/답변/응답',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ',
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	PRIMARY KEY (ANSWER_SEQ)
) COMMENT = '대상자 답변';


-- 파일 정보
CREATE TABLE ATTACHFILE
(
	-- 파일을 N:N 관계로 연계 위해 추가
	ATTACHFILE_SEQ varchar(40) NOT NULL COMMENT '첨부파일 일련번호',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 원본파일_명
	ORGINAL_NAME varchar(200) NOT NULL COMMENT '원본 파일명',
	-- 서비 저장 위한 변환된 파일명
	PHYSICAL_NAME varchar(200) NOT NULL COMMENT '변환된 파일명',
	-- 썸네일 첨부파일명
	THUMBNAIL_NAME varchar(500) COMMENT '썸네일 첨부파일명',
	-- 저장경로
	PATH varchar(500) NOT NULL COMMENT '저장경로',
	PRIMARY KEY (ATTACHFILE_SEQ)
) COMMENT = '파일 정보';


-- 출석부
CREATE TABLE ATTENDANCE
(
	-- 출석부 SEQ
	ATTENDANCE_SEQ varchar(40) NOT NULL COMMENT '출석부 SEQ',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	PRIMARY KEY (ATTENDANCE_SEQ)
) COMMENT = '출석부';


-- 권한 종류
CREATE TABLE AUTHORITY
(
	-- 권한 종류 ID
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 종류 ID',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	PRIMARY KEY (AUTHORITY_ID)
) COMMENT = '권한 종류';


-- 회원별 권한
CREATE TABLE AUTHORITY_MEMBER
(
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	-- 권한 종류 ID
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 종류 ID',
	UNIQUE (MEMBER_SEQ, AUTHORITY_ID)
) COMMENT = '회원별 권한';


-- 공통코드
CREATE TABLE COMMONCODE
(
	-- 공통코드_ID (사용자 입력 가능)
	COMMONCODE_ID varchar(40) NOT NULL COMMENT '공통코드_ID',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 삭제불가(시스템 코드 or 카테고리)
	SYSTEM_CODE_YN varchar(40) DEFAULT 'N' NOT NULL COMMENT '시스템 코드 여부',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) DEFAULT 'Y' NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 상위 코드 ID
	PARENT_COMMONCODE_ID varchar(40) COMMENT '상위 코드 ID',
	PRIMARY KEY (COMMONCODE_ID)
) COMMENT = '공통코드';


-- 각종 접근 정보
CREATE TABLE CONTACTMISC
(
	-- 각종 접근 정보 SEQ
	CONTACTMISC_SEQ varchar(40) NOT NULL COMMENT '각종 접근 정보 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 각종 정보
	INFORMATION varchar(2000) NOT NULL COMMENT '정보',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) DEFAULT 'Y' NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	PRIMARY KEY (CONTACTMISC_SEQ)
) COMMENT = '각종 접근 정보';


-- 기관간 협력
CREATE TABLE COOPERATION
(
	-- 기관간 협력 SEQ
	COOPERATION_SEQ varchar(40) NOT NULL COMMENT '기관간 협력 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 금액/부담금 
	PRICE decimal COMMENT '금액/부담금',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	PRIMARY KEY (COOPERATION_SEQ)
) COMMENT = '기관간 협력';


-- 개설 과정/과목
CREATE TABLE COURSE
(
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) NOT NULL COMMENT '종료일시',
	-- 시작 시각
	START_TIME varchar(12) COMMENT '시작 시각',
	-- 종료 시각
	END_TIME varchar(12) COMMENT '종료 시각',
	-- 상위 과정/과목 SEQ
	PARENT_COURSE_SEQ varchar(40) COMMENT '상위 과정/과목 SEQ',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	PRIMARY KEY (COURSE_SEQ)
) COMMENT = '개설 과정/과목';


-- 과정/과목 은행
CREATE TABLE COURSEBANK
(
	-- 과정/과목 은행 SEQ
	COURSEBANK_SEQ varchar(40) NOT NULL COMMENT '과정/과목 은행 SEQ',
	-- 정렬순서
	ORDER_NUMBER decimal NOT NULL COMMENT '정렬순서',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal NOT NULL COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 시작 시각
	START_TIME varchar(12) NOT NULL COMMENT '시작 시각',
	-- 종료 시각
	END_TIME varchar(12) COMMENT '종료 시각',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 상위 과정/과목 은행 SEQ
	PARENT_COURSEBANK_SEQ varchar(40) COMMENT '상위 과정/과목 은행 SEQ',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	PRIMARY KEY (COURSEBANK_SEQ)
) COMMENT = '과정/과목 은행';


-- 과정 은행 사용 내역
CREATE TABLE COURSEBANK_COURSE
(
	-- 과정/과목 은행 SEQ
	COURSEBANK_SEQ varchar(40) NOT NULL COMMENT '과정/과목 은행 SEQ',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ'
) COMMENT = '과정 은행 사용 내역';


-- 과정/과목 은행 질의
CREATE TABLE COURSEBANK_QUESTIONBANK
(
	-- 과정/과목 은행 질의문 SEQ
	COURSEBANK_QUESTIONBANK_SEQ varchar(40) NOT NULL COMMENT '과정/과목 은행 질의문 SEQ',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal NOT NULL COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 과정/과목 은행 SEQ
	COURSEBANK_SEQ varchar(40) NOT NULL COMMENT '과정/과목 은행 SEQ',
	-- 각종 질의 은행 SEQ
	QUESTIONBANK_SEQ varchar(40) NOT NULL COMMENT '각종 질의 은행 SEQ',
	PRIMARY KEY (COURSEBANK_QUESTIONBANK_SEQ)
) COMMENT = '과정/과목 은행 질의';


-- 과정 및 과목 은행별 사용교재
CREATE TABLE COURSEBANK_TEACHINGMATERIAL
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 사용 교자재 SEQ
	TEACHINGMATERIAL_SEQ varchar(40) NOT NULL COMMENT '사용 교자재 SEQ'
) COMMENT = '과정 및 과목 은행별 사용교재';


-- 개설 과정/과목 질의
CREATE TABLE COURSE_QUESTION
(
	-- 개설 과정/과목 질의 SEQ
	COURSE_QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 질의 SEQ',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) COMMENT '종료일시',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ',
	PRIMARY KEY (COURSE_QUESTION_SEQ)
) COMMENT = '개설 과정/과목 질의';


-- 질의 평가 종합
CREATE TABLE EVALUATION
(
	-- 질의 평가 종합 SEQ
	EVALUATION_SEQ varchar(40) NOT NULL COMMENT '질의 평가 종합 SEQ',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ',
	PRIMARY KEY (EVALUATION_SEQ)
) COMMENT = '질의 평가 종합';


-- 예외 일시(식사 등)
CREATE TABLE EXCEPTEDDATE
(
	-- 예외 일시 SEQ
	EXCEPTEDDATE_SEQ varchar(40) NOT NULL COMMENT '예외 일시 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) COMMENT '종료일시',
	PRIMARY KEY (EXCEPTEDDATE_SEQ)
) COMMENT = '예외 일시(식사 등)';


-- 각종 시설
CREATE TABLE FACILITY
(
	-- 각종 시설 SEQ
	FACILITY_SEQ varchar(40) NOT NULL COMMENT '각종 시설 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 크기
	SIZE decimal COMMENT '크기',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 경도
	LONGITUDE varchar(50) COMMENT '경도',
	-- 위도
	LATITUDE varchar(50) COMMENT '위도',
	-- 상위 각종 시설 SEQ
	PARENT_FACILITY_SEQ varchar(40) COMMENT '상위 각종 시설 SEQ',
	PRIMARY KEY (FACILITY_SEQ)
) COMMENT = '각종 시설';


-- 해쉬태그
CREATE TABLE HASHTAG
(
	-- 해쉬테그 SEQ
	HASHTAG_SEQ varchar(40) NOT NULL COMMENT '해쉬테그 SEQ',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	PRIMARY KEY (HASHTAG_SEQ)
) COMMENT = '해쉬태그';


-- 바우처 종류 그룹
CREATE TABLE KINDVOUCHERGROUP
(
	-- 바우처 그룹 SEQ
	KINDVOUCHERGROUP_SEQ varchar(40) NOT NULL COMMENT '바우처 그룹 SEQ',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 금액/부담금 
	PRICE decimal COMMENT '금액/부담금',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	PRIMARY KEY (KINDVOUCHERGROUP_SEQ)
) COMMENT = '바우처 종류 그룹';


-- 강의 구성원
CREATE TABLE LECTURE_MEMBER
(
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 상태/에러상태
	STATUS varchar(40) COMMENT '상태/에러상태',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	PRIMARY KEY (LECTURE_MEMBER_SEQ)
) COMMENT = '강의 구성원';


-- 연결 위치 정보
CREATE TABLE LOCATIONTRACE
(
	-- 연결 위치 정보 SEQ
	LOCATIONTRACE_SEQ varchar(40) NOT NULL COMMENT '연결 위치 정보 SEQ',
	-- 위도
	LATITUDE varchar(50) NOT NULL COMMENT '위도',
	-- 경도
	LONGITUDE varchar(50) NOT NULL COMMENT '경도',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	PRIMARY KEY (LOCATIONTRACE_SEQ)
) COMMENT = '연결 위치 정보';


-- 회원정보
CREATE TABLE MEMBER
(
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	-- 회원_ID
	MEMBER_ID varchar(50) NOT NULL COMMENT '회원 ID',
	-- 암호화된 암호
	CRYPT_PASSWORD varchar(100) NOT NULL COMMENT '암호화된 암호',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 휴대폰/전화번호
	PHONE_NUMBER varchar(20) COMMENT '휴대폰/전화번호',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 임시저장여부
	TEMPORARY_YN varchar(40) NOT NULL COMMENT '임시저장여부',
	PRIMARY KEY (MEMBER_SEQ),
	UNIQUE (MEMBER_ID)
) COMMENT = '회원정보';


-- 메뉴 마스터 정보
CREATE TABLE MENU
(
	-- 메뉴 코드 FULL URI
	MENU_ID varchar(100) NOT NULL COMMENT '메뉴 코드 ID',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) DEFAULT 'Y' COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 메뉴 코드 FULL URI
	PARENT_MENU_ID varchar(100) COMMENT '상위 메뉴 코드 ID',
	PRIMARY KEY (MENU_ID)
) COMMENT = '메뉴 마스터 정보';


-- 메뉴 따른 권한
CREATE TABLE MENU_AUTHORITY
(
	-- 메뉴 따른 권한 SEQ
	MENU_AUTHORITY_SEQ varchar(40) NOT NULL COMMENT '메뉴 따른 권한 SEQ',
	-- 권한 종류 ID
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 종류 ID',
	-- 메뉴 코드 FULL URI
	MENU_ID varchar(100) NOT NULL COMMENT '메뉴 코드 ID',
	PRIMARY KEY (MENU_AUTHORITY_SEQ)
) COMMENT = '메뉴 따른 권한';


-- 메세지 형식
CREATE TABLE MESSAGEFORM
(
	-- 메세지 형식 ID
	MESSAGEFORM_ID varchar(40) NOT NULL COMMENT '메세지 형식 ID',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 제목
	TITLE varchar(4000) COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) NOT NULL COMMENT '내용/댓글/설명',
	-- 삭제불가(시스템 코드 or 카테고리)
	SYSTEM_CODE_YN varchar(40) COMMENT '시스템 코드 여부',
	CONSTRAINT PK_MULTI_BOARD PRIMARY KEY (MESSAGEFORM_ID)
) COMMENT = '메세지 형식';


-- 메세지 받는 허용 방법
CREATE TABLE MESSAGERECEIVEWAY
(
	-- 메세지 받는 허용 방법 SEQ
	MESSAGERECEIVEWAY_SEQ varchar(40) NOT NULL COMMENT '메세지 받는 허용 방법 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	PRIMARY KEY (MESSAGERECEIVEWAY_SEQ)
) COMMENT = '메세지 받는 허용 방법';


-- 멀티게시판
CREATE TABLE MULTIBOARD
(
	-- 게시물 일련번호
	MULTIBOARD_SEQ varchar(40) NOT NULL COMMENT '게시물 일련번호',
	-- 제목
	TITLE varchar(4000) COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) NOT NULL COMMENT '내용/댓글/설명',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) COMMENT '종료일시',
	-- 암호화된 암호
	CRYPT_PASSWORD varchar(100) COMMENT '암호화된 암호',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) COMMENT '회원 SEQ',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 수정일자
	MODIFY_DATE datetime NOT NULL COMMENT '수정일자',
	-- 상위 게시물 일련번호
	PARENT_MULTIBOARD_SEQ varchar(40) COMMENT '상위 게시물 일련번호',
	-- 멀티 게시판 그룹 ID
	MULTI_BOARDGROUP_ID varchar(40) NOT NULL COMMENT '멀티 게시판 그룹 ID',
	CONSTRAINT PK_MULTI_BOARD PRIMARY KEY (MULTIBOARD_SEQ)
) COMMENT = '멀티게시판';


-- 멀티게시판그룹
CREATE TABLE MULTIBOARDGROUP
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 멀티 게시판 그룹 ID
	MULTI_BOARDGROUP_ID varchar(40) NOT NULL COMMENT '멀티 게시판 그룹 ID',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	PRIMARY KEY (MULTI_BOARDGROUP_ID),
	UNIQUE (RELATEDTABLE_SEQ)
) COMMENT = '멀티게시판그룹';


-- 게시판 검색 해쉬태그
CREATE TABLE MULTIBOARD_HASHTAG
(
	-- 게시물 일련번호
	MULTIBOARD_SEQ varchar(40) NOT NULL COMMENT '게시물 일련번호',
	-- 해쉬테그 SEQ
	HASHTAG_SEQ varchar(40) NOT NULL COMMENT '해쉬테그 SEQ'
) COMMENT = '게시판 검색 해쉬태그';


-- 국가달력(API)
CREATE TABLE NATIONALCALENDAR_API
(
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부'
) COMMENT = '국가달력(API)';


-- NCS 코드
CREATE TABLE NCSCODE
(
	-- NCS코드 SEQ
	NCSCODE_SEQ varchar(40) NOT NULL COMMENT 'NCS코드 SEQ',
	-- 공통코드_ID (사용자 입력 가능)
	COMMONCODE_ID varchar(40) NOT NULL COMMENT '공통코드_ID',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 상위 NCS코드 SEQ
	PARENT_NCSCODE_SEQ varchar(40) COMMENT '상위 NCS코드 SEQ',
	PRIMARY KEY (NCSCODE_SEQ)
) COMMENT = 'NCS 코드';


-- 개설강좌 강의실
CREATE TABLE OPENCOURSE_FACILITY
(
	-- 개설강좌 강의실 SEQ
	OPENCOURSE_FACILITY_SEQ varchar(40) NOT NULL COMMENT '개설강좌 강의실 SEQ',
	-- 각종 시설 SEQ
	FACILITY_SEQ varchar(40) NOT NULL COMMENT '각종 시설 SEQ',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	PRIMARY KEY (OPENCOURSE_FACILITY_SEQ)
) COMMENT = '개설강좌 강의실';


-- 기관/그룹/조직/부서 구조도
CREATE TABLE ORGANIZATION
(
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- EMAIL
	EMAIL varchar(1000) COMMENT 'EMAIL',
	-- 휴대폰/전화번호
	PHONE_NUMBER varchar(20) COMMENT '휴대폰/전화번호',
	-- 등록번호/사업번호
	LICENSE_NUMBER varchar(40) COMMENT '등록번호/사업번호',
	-- URI
	URI varchar(2000) COMMENT 'URI',
	-- 임시저장여부
	TEMPORARY_YN varchar(40) NOT NULL COMMENT '임시저장여부',
	-- 상위 조직 일련번호
	PARENT_ORGANIZATION_SEQ varchar(40) COMMENT '상위 조직 일련번호',
	CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ORGANIZATION_SEQ)
) COMMENT = '기관/그룹/조직/부서 구조도';


-- 개설 강좌 모집 정보
CREATE TABLE ORGANIZATION_COURSE
(
	-- 기관 개설 강좌 SEQ
	ORGANIZATION_COURSE_SEQ varchar(40) NOT NULL COMMENT '기관 개설 강좌 SEQ',
	-- 모집 시작일시
	RECRUIT_START_DATE varchar(12) NOT NULL COMMENT '모집 시작일시',
	-- 모집 종료일시
	RECRUIT_END_DATE varchar(12) NOT NULL COMMENT '모집 종료일시',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal NOT NULL COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) COMMENT '종류or형식or유형',
	-- 금액/부담금 
	PRICE decimal COMMENT '금액/부담금',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) NOT NULL COMMENT '개설 과정/과목 SEQ',
	PRIMARY KEY (ORGANIZATION_COURSE_SEQ)
) COMMENT = '개설 강좌 모집 정보';


-- 기관 판매 과정은행
CREATE TABLE ORGANIZATION_COURSEBANK
(
	-- 기관 판매 과정 은행 SEQ
	ORGANIZATION_COURSEBANK_SEQ varchar(40) NOT NULL COMMENT '기관 판매 과정 은행 SEQ',
	-- 금액/부담금 
	PRICE decimal COMMENT '금액/부담금',
	-- 상위 기관 보유 과정 은행 SEQ
	PARENT_ORGANIZATION_COURSEBANK_SEQ varchar(40) COMMENT '상위 기관 보유 과정 은행 SEQ',
	-- 과정/과목 은행 SEQ
	COURSEBANK_SEQ varchar(40) NOT NULL COMMENT '과정/과목 은행 SEQ',
	PRIMARY KEY (ORGANIZATION_COURSEBANK_SEQ)
) COMMENT = '기관 판매 과정은행';


-- 기관 시설
CREATE TABLE ORGANIZATION_FACILITY
(
	-- 기관 보유 시설 SEQ
	ORGANIZATION_FACILITY_SEQ varchar(40) NOT NULL COMMENT '기관 보유 시설 SEQ',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	-- 각종 시설 SEQ
	FACILITY_SEQ varchar(40) NOT NULL COMMENT '각종 시설 SEQ',
	PRIMARY KEY (ORGANIZATION_FACILITY_SEQ)
) COMMENT = '기관 시설';


-- 조직 근무자
CREATE TABLE ORGANIZATION_MEMBER
(
	-- 조직 근무자 SEQ
	ORGANIZATION_MEMBER_SEQ varchar(40) NOT NULL COMMENT '조직 근무자 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	PRIMARY KEY (ORGANIZATION_MEMBER_SEQ)
) COMMENT = '조직 근무자';


-- 수행프로젝트정보
CREATE TABLE PROJECT
(
	-- 프로젝트_SEQ
	PROJECT_SEQ varchar(40) NOT NULL COMMENT '프로젝트 일련번호',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- URI
	URI varchar(2000) COMMENT 'URI',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) COMMENT '종료일시',
	-- 정렬순서
	ORDER_NUMBER decimal DEFAULT 0 COMMENT '정렬순서',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ',
	-- 상위 프로젝트_SEQ
	PARENT_PROJECT_SEQ varchar(40) COMMENT '프로젝트 일련번호',
	PRIMARY KEY (PROJECT_SEQ)
) COMMENT = '수행프로젝트정보';


-- 프로젝트 구성원
CREATE TABLE PROJECT_MEMBER
(
	-- 프로젝트 구성원 SEQ
	PROJECT_MEMBER_SEQ varchar(40) NOT NULL COMMENT '프로젝트 구성원 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) COMMENT '종류or형식or유형',
	-- 과목 강의 구성원 SEQ
	LECTURE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '과목 강의 구성원 SEQ',
	-- 프로젝트_SEQ
	PROJECT_SEQ varchar(40) NOT NULL COMMENT '프로젝트 일련번호',
	PRIMARY KEY (PROJECT_MEMBER_SEQ)
) COMMENT = '프로젝트 구성원';


-- 발행바우처
CREATE TABLE PUBLICVOUCHER
(
	-- 발행 바우처 SEQ
	PUBLICVOUCHER_SEQ varchar(40) NOT NULL COMMENT '발행 바우처 SEQ',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) NOT NULL COMMENT '종료일시',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal NOT NULL COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 사용/공개/대표/합격/승인/모집/해답 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용/공개/대표/합격/승인/모집/해답 여부',
	-- 바우처 그룹 SEQ
	KINDVOUCHERGROUP_SEQ varchar(40) NOT NULL COMMENT '바우처 그룹 SEQ',
	PRIMARY KEY (PUBLICVOUCHER_SEQ)
) COMMENT = '발행바우처';


-- 개설과목 질의
CREATE TABLE QUESTION
(
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 정렬순서
	ORDER_NUMBER decimal NOT NULL COMMENT '정렬순서',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 점수가중치
	WEIGHT decimal COMMENT '점수가중치',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 상위 개설과목 질의 SEQ
	PARENT_QUESTION_SEQ varchar(40) COMMENT '상위 개설과목 질의 SEQ',
	PRIMARY KEY (QUESTION_SEQ)
) COMMENT = '개설과목 질의';


-- 각종 질의 은행
CREATE TABLE QUESTIONBANK
(
	-- 각종 질의 은행 SEQ
	QUESTIONBANK_SEQ varchar(40) NOT NULL COMMENT '각종 질의 은행 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 점수가중치
	WEIGHT decimal COMMENT '점수가중치',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 상위 각종 질의 은행 SEQ
	PARENT_QUESTIONBANK_SEQ varchar(40) COMMENT '상위 각종 질의 은행 SEQ',
	PRIMARY KEY (QUESTIONBANK_SEQ)
) COMMENT = '각종 질의 은행';


-- 각종 질의 은행 사용 내역
CREATE TABLE QUESTIONBANK_QUESTION
(
	-- 각종 질의 은행 SEQ
	QUESTIONBANK_SEQ varchar(40) NOT NULL COMMENT '각종 질의 은행 SEQ',
	-- 개설과목 질의 SEQ
	QUESTION_SEQ varchar(40) NOT NULL COMMENT '개설과목 질의 SEQ'
) COMMENT = '각종 질의 은행 사용 내역';


-- 각종 질의 평가기준표
CREATE TABLE QUESTION_STANDARDEVALUATION
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 평가 기준표 ID
	STANDARDEVALUATION_ID varchar(40) NOT NULL COMMENT '평가 기준표 ID'
) COMMENT = '각종 질의 평가기준표';


-- 각종 회원 참조 정보
CREATE TABLE REFERENCEMEMBER
(
	-- 각종 회원 참조 정보 SEQ
	REFERENCEMEMBER_SEQ varchar(40) NOT NULL COMMENT '각종 참조 정보 SEQ',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) NOT NULL COMMENT '종료일시',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	-- 개설 과정/과목 SEQ
	COURSE_SEQ varchar(40) COMMENT '개설 과정/과목 SEQ',
	PRIMARY KEY (REFERENCEMEMBER_SEQ)
) COMMENT = '각종 회원 참조 정보';


-- 연관된 파일 정보
CREATE TABLE RELATEDATTACHFILE
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 파일을 N:N 관계로 연계 위해 추가
	ATTACHFILE_SEQ varchar(40) NOT NULL COMMENT '첨부파일 일련번호',
	UNIQUE (RELATEDTABLE_SEQ, ATTACHFILE_SEQ)
) COMMENT = '연관된 파일 정보';


-- 연관된 각종 접근 테이블 정보
CREATE TABLE RELATEDCONTACTMISC
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 각종 접근 정보 SEQ
	CONTACTMISC_SEQ varchar(40) NOT NULL COMMENT '각종 접근 정보 SEQ'
) COMMENT = '연관된 각종 접근 테이블 정보';


-- 연결되는 예외 일시
CREATE TABLE RELATEDEXCEPTEDDATE
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- 예외 일시 SEQ
	EXCEPTEDDATE_SEQ varchar(40) NOT NULL COMMENT '예외 일시 SEQ'
) COMMENT = '연결되는 예외 일시';


-- 연관된 NCS코드
CREATE TABLE RELATEDNCSCODE
(
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) NOT NULL COMMENT '연관된 테이블 SEQ',
	-- NCS코드 SEQ
	NCSCODE_SEQ varchar(40) NOT NULL COMMENT 'NCS코드 SEQ'
) COMMENT = '연관된 NCS코드';


-- 보낸 메세지 목록
CREATE TABLE SENDEDMESSAGE
(
	-- 보낸 메세지 목록 SEQ
	SENDEDMESSAGE_SEQ varchar(40) NOT NULL COMMENT '보낸 메세지 목록 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 종류(메세지,규격,출결,답변대상자)
	KIND varchar(40) NOT NULL COMMENT '종류(메세지,규격,출결,답변대상자)',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- 시작일시 (공지 등) or 일단위 의미
	START_DATE varchar(12) NOT NULL COMMENT '시작일시',
	-- 종료일시 (공지 등)
	END_DATE varchar(12) COMMENT '종료일시',
	-- 연관된 테이블 SEQ
	RELATEDTABLE_SEQ varchar(40) COMMENT '연관된 테이블 SEQ',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	PRIMARY KEY (SENDEDMESSAGE_SEQ)
) COMMENT = '보낸 메세지 목록';


-- 보낸 메세지 회원
CREATE TABLE SENDEDMESSAGE_MEMBER
(
	-- 보낸 메세지 회원 SEQ
	SENDEDMESSAGE_MEMBER_SEQ varchar(40) NOT NULL COMMENT '보낸 메세지 회원 SEQ',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 상태/에러상태
	STATUS varchar(40) COMMENT '상태/에러상태',
	-- 회원 SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원 SEQ',
	-- 보낸 메세지 목록 SEQ
	SENDEDMESSAGE_SEQ varchar(40) NOT NULL COMMENT '보낸 메세지 목록 SEQ',
	PRIMARY KEY (SENDEDMESSAGE_MEMBER_SEQ)
) COMMENT = '보낸 메세지 회원';


-- 평가기준표
CREATE TABLE STANDARDEVALUATION
(
	-- 평가 기준표 ID
	STANDARDEVALUATION_ID varchar(40) NOT NULL COMMENT '평가 기준표 ID',
	-- 제목
	TITLE varchar(4000) NOT NULL COMMENT '제목',
	-- 갯수 or 점수 or 일수 or 인원수
	COUNT decimal NOT NULL COMMENT '갯수 or 점수 or 일수 or 인원수',
	-- 정렬순서
	ORDER_NUMBER decimal NOT NULL COMMENT '정렬순서',
	-- 상위 평가 기준표 ID
	PARENT_STANDARDEVALUATION_ID varchar(40) COMMENT '상위 평가 기준표 ID',
	PRIMARY KEY (STANDARDEVALUATION_ID)
) COMMENT = '평가기준표';


-- 보유 바우처
CREATE TABLE TAKEVOUCHER
(
	-- 보유 바우처 SEQ
	TAKEVOUCHER_SEQ varchar(40) NOT NULL COMMENT '보유 바우처 SEQ',
	-- 종류 or 형식 from common code or 유형
	TYPE varchar(40) NOT NULL COMMENT '종류or형식or유형',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 발행 바우처 SEQ
	PUBLICVOUCHER_SEQ varchar(40) NOT NULL COMMENT '발행 바우처 SEQ',
	-- 기관/조직 일련번호
	ORGANIZATION_SEQ varchar(40) NOT NULL COMMENT '기관/조직 일련번호',
	PRIMARY KEY (TAKEVOUCHER_SEQ)
) COMMENT = '보유 바우처';


-- 사용교자재
CREATE TABLE TEACHINGMATERIAL
(
	-- 사용 교자재 SEQ
	TEACHINGMATERIAL_SEQ varchar(40) NOT NULL COMMENT '사용 교자재 SEQ',
	-- 명칭/팀명/해쉬태그/강의실번호/팀명 
	NAME varchar(255) NOT NULL COMMENT '명칭/팀명/해쉬태그/강의실번호/팀명',
	-- 내용/댓글/설명
	CONTENT varchar(9000) COMMENT '내용/댓글/설명',
	-- URI
	URI varchar(2000) COMMENT 'URI',
	PRIMARY KEY (TEACHINGMATERIAL_SEQ)
) COMMENT = '사용교자재';


-- 사용 바우처
CREATE TABLE USEVOUCHER
(
	-- 사용 바우처 SEQ
	USEVOUCHER_SEQ varchar(40) NOT NULL COMMENT '사용 바우처 SEQ',
	-- 금액/부담금 
	PRICE decimal COMMENT '금액/부담금',
	-- 등록일자
	REGISTRY_DATE datetime NOT NULL COMMENT '등록일자',
	-- 보유 바우처 SEQ
	TAKEVOUCHER_SEQ varchar(40) NOT NULL COMMENT '보유 바우처 SEQ',
	PRIMARY KEY (USEVOUCHER_SEQ)
) COMMENT = '사용 바우처';



/* Create Foreign Keys */

ALTER TABLE RELATEDATTACHFILE
	ADD FOREIGN KEY (ATTACHFILE_SEQ)
	REFERENCES ATTACHFILE (ATTACHFILE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES AUTHORITY (AUTHORITY_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MENU_AUTHORITY
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES AUTHORITY (AUTHORITY_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COMMONCODE
	ADD FOREIGN KEY (PARENT_COMMONCODE_ID)
	REFERENCES COMMONCODE (COMMONCODE_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE RELATEDCONTACTMISC
	ADD FOREIGN KEY (CONTACTMISC_SEQ)
	REFERENCES CONTACTMISC (CONTACTMISC_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ATTENDANCE
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSE
	ADD FOREIGN KEY (PARENT_COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK_COURSE
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSE_QUESTION
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE LECTURE_MEMBER
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE OPENCOURSE_FACILITY
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_COURSE
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE REFERENCEMEMBER
	ADD FOREIGN KEY (COURSE_SEQ)
	REFERENCES COURSE (COURSE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK
	ADD FOREIGN KEY (PARENT_COURSEBANK_SEQ)
	REFERENCES COURSEBANK (COURSEBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK_COURSE
	ADD FOREIGN KEY (COURSEBANK_SEQ)
	REFERENCES COURSEBANK (COURSEBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK_QUESTIONBANK
	ADD FOREIGN KEY (COURSEBANK_SEQ)
	REFERENCES COURSEBANK (COURSEBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_COURSEBANK
	ADD FOREIGN KEY (COURSEBANK_SEQ)
	REFERENCES COURSEBANK (COURSEBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE RELATEDEXCEPTEDDATE
	ADD FOREIGN KEY (EXCEPTEDDATE_SEQ)
	REFERENCES EXCEPTEDDATE (EXCEPTEDDATE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE FACILITY
	ADD FOREIGN KEY (PARENT_FACILITY_SEQ)
	REFERENCES FACILITY (FACILITY_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE OPENCOURSE_FACILITY
	ADD FOREIGN KEY (FACILITY_SEQ)
	REFERENCES FACILITY (FACILITY_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_FACILITY
	ADD FOREIGN KEY (FACILITY_SEQ)
	REFERENCES FACILITY (FACILITY_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MULTIBOARD_HASHTAG
	ADD FOREIGN KEY (HASHTAG_SEQ)
	REFERENCES HASHTAG (HASHTAG_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE PUBLICVOUCHER
	ADD FOREIGN KEY (KINDVOUCHERGROUP_SEQ)
	REFERENCES KINDVOUCHERGROUP (KINDVOUCHERGROUP_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (LECTURE_MEMBER_SEQ)
	REFERENCES LECTURE_MEMBER (LECTURE_MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ATTENDANCE
	ADD FOREIGN KEY (LECTURE_MEMBER_SEQ)
	REFERENCES LECTURE_MEMBER (LECTURE_MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COOPERATION
	ADD FOREIGN KEY (LECTURE_MEMBER_SEQ)
	REFERENCES LECTURE_MEMBER (LECTURE_MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE EVALUATION
	ADD FOREIGN KEY (LECTURE_MEMBER_SEQ)
	REFERENCES LECTURE_MEMBER (LECTURE_MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE PROJECT_MEMBER
	ADD FOREIGN KEY (LECTURE_MEMBER_SEQ)
	REFERENCES LECTURE_MEMBER (LECTURE_MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE LECTURE_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE LOCATIONTRACE
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MESSAGERECEIVEWAY
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE REFERENCEMEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE SENDEDMESSAGE_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MENU
	ADD FOREIGN KEY (PARENT_MENU_ID)
	REFERENCES MENU (MENU_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MENU_AUTHORITY
	ADD FOREIGN KEY (MENU_ID)
	REFERENCES MENU (MENU_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MULTIBOARD
	ADD FOREIGN KEY (PARENT_MULTIBOARD_SEQ)
	REFERENCES MULTIBOARD (MULTIBOARD_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MULTIBOARD_HASHTAG
	ADD FOREIGN KEY (MULTIBOARD_SEQ)
	REFERENCES MULTIBOARD (MULTIBOARD_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE MULTIBOARD
	ADD FOREIGN KEY (MULTI_BOARDGROUP_ID)
	REFERENCES MULTIBOARDGROUP (MULTI_BOARDGROUP_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE NCSCODE
	ADD FOREIGN KEY (PARENT_NCSCODE_SEQ)
	REFERENCES NCSCODE (NCSCODE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE RELATEDNCSCODE
	ADD FOREIGN KEY (NCSCODE_SEQ)
	REFERENCES NCSCODE (NCSCODE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COOPERATION
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSE
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION
	ADD FOREIGN KEY (PARENT_ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_FACILITY
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_MEMBER
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE SENDEDMESSAGE
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE TAKEVOUCHER
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ORGANIZATION_COURSEBANK
	ADD FOREIGN KEY (PARENT_ORGANIZATION_COURSEBANK_SEQ)
	REFERENCES ORGANIZATION_COURSEBANK (ORGANIZATION_COURSEBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE PROJECT
	ADD FOREIGN KEY (PARENT_PROJECT_SEQ)
	REFERENCES PROJECT (PROJECT_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE PROJECT_MEMBER
	ADD FOREIGN KEY (PROJECT_SEQ)
	REFERENCES PROJECT (PROJECT_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE TAKEVOUCHER
	ADD FOREIGN KEY (PUBLICVOUCHER_SEQ)
	REFERENCES PUBLICVOUCHER (PUBLICVOUCHER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSE_QUESTION
	ADD FOREIGN KEY (QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE EVALUATION
	ADD FOREIGN KEY (QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE PROJECT
	ADD FOREIGN KEY (QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (PARENT_QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE QUESTIONBANK_QUESTION
	ADD FOREIGN KEY (QUESTION_SEQ)
	REFERENCES QUESTION (QUESTION_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK_QUESTIONBANK
	ADD FOREIGN KEY (QUESTIONBANK_SEQ)
	REFERENCES QUESTIONBANK (QUESTIONBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE QUESTIONBANK
	ADD FOREIGN KEY (PARENT_QUESTIONBANK_SEQ)
	REFERENCES QUESTIONBANK (QUESTIONBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE QUESTIONBANK_QUESTION
	ADD FOREIGN KEY (QUESTIONBANK_SEQ)
	REFERENCES QUESTIONBANK (QUESTIONBANK_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE SENDEDMESSAGE_MEMBER
	ADD FOREIGN KEY (SENDEDMESSAGE_SEQ)
	REFERENCES SENDEDMESSAGE (SENDEDMESSAGE_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE QUESTION_STANDARDEVALUATION
	ADD FOREIGN KEY (STANDARDEVALUATION_ID)
	REFERENCES STANDARDEVALUATION (STANDARDEVALUATION_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE STANDARDEVALUATION
	ADD FOREIGN KEY (PARENT_STANDARDEVALUATION_ID)
	REFERENCES STANDARDEVALUATION (STANDARDEVALUATION_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE USEVOUCHER
	ADD FOREIGN KEY (TAKEVOUCHER_SEQ)
	REFERENCES TAKEVOUCHER (TAKEVOUCHER_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE COURSEBANK_TEACHINGMATERIAL
	ADD FOREIGN KEY (TEACHINGMATERIAL_SEQ)
	REFERENCES TEACHINGMATERIAL (TEACHINGMATERIAL_SEQ)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;



/* Create Indexes */

CREATE INDEX ANSWER_INX01 ON ANSWER (QUESTION_SEQ ASC, LECTURE_MEMBER_SEQ ASC);
CREATE UNIQUE INDEX ATTENDANCE_INX01 ON ATTENDANCE (LECTURE_MEMBER_SEQ ASC, COURSE_SEQ ASC, REGISTRY_DATE ASC);
CREATE UNIQUE INDEX ATTENDANCE_INX02 ON ATTENDANCE (COURSE_SEQ ASC, LECTURE_MEMBER_SEQ ASC, REGISTRY_DATE ASC);
CREATE UNIQUE INDEX COMMONCODE_INX01 ON COMMONCODE (PARENT_COMMONCODE_ID ASC, COMMONCODE_ID ASC);
CREATE UNIQUE INDEX COOPERATION_INX01 ON COOPERATION (ORGANIZATION_SEQ ASC, LECTURE_MEMBER_SEQ ASC, COOPERATION_SEQ ASC);
CREATE UNIQUE INDEX COURSE_INX01 ON COURSE (PARENT_COURSE_SEQ ASC, COURSE_SEQ ASC);
CREATE UNIQUE INDEX COURSEBANK_INX01 ON COURSEBANK (PARENT_COURSEBANK_SEQ ASC, COURSEBANK_SEQ ASC);
CREATE UNIQUE INDEX COURSEBANK_QUESTIONBANK_IDX01 ON COURSEBANK_QUESTIONBANK (COURSEBANK_SEQ ASC, QUESTIONBANK_SEQ ASC);
CREATE UNIQUE INDEX COURSEBANK_TEACHINGMATERIAL_INX01 ON COURSEBANK_TEACHINGMATERIAL (RELATEDTABLE_SEQ ASC, TEACHINGMATERIAL_SEQ ASC);
CREATE UNIQUE INDEX EVALUATION_INX01 ON EVALUATION (LECTURE_MEMBER_SEQ ASC, QUESTION_SEQ ASC);
CREATE UNIQUE INDEX EVALUATION_INX02 ON EVALUATION (QUESTION_SEQ ASC, LECTURE_MEMBER_SEQ ASC);
CREATE UNIQUE INDEX FACILITY_INX01 ON FACILITY (PARENT_FACILITY_SEQ ASC, FACILITY_SEQ ASC);
CREATE UNIQUE INDEX LECTURE_MEMBER_INX01 ON LECTURE_MEMBER (COURSE_SEQ ASC, MEMBER_SEQ ASC, TYPE ASC);
CREATE UNIQUE INDEX LECTURE_MEMBER_INX02 ON LECTURE_MEMBER (MEMBER_SEQ ASC, COURSE_SEQ ASC, TYPE ASC);
CREATE UNIQUE INDEX MENU_INX01 ON MENU (PARENT_MENU_ID ASC, MENU_ID ASC);
CREATE UNIQUE INDEX MENU_AUTHORITY_INX01 ON MENU_AUTHORITY (AUTHORITY_ID ASC, MENU_ID ASC);
CREATE UNIQUE INDEX MENU_AUTHORITY_INX02 ON MENU_AUTHORITY (MENU_ID ASC, AUTHORITY_ID ASC);
CREATE UNIQUE INDEX MULTIBOARD_INX01 ON MULTIBOARD (PARENT_MULTIBOARD_SEQ ASC, MULTIBOARD_SEQ ASC);
CREATE UNIQUE INDEX MULTIBOARD_INX02 ON MULTIBOARD (MULTI_BOARDGROUP_ID ASC, MULTIBOARD_SEQ ASC);
CREATE UNIQUE INDEX MULTIBOARDGROUP_INX01 ON MULTIBOARDGROUP (RELATEDTABLE_SEQ ASC, MULTI_BOARDGROUP_ID ASC);
CREATE UNIQUE INDEX NATIONALCALENDAR_API ON NATIONALCALENDAR_API (START_DATE ASC, NAME ASC);
CREATE UNIQUE INDEX NCSCODE_INX01 ON NCSCODE (PARENT_NCSCODE_SEQ ASC, NCSCODE_SEQ ASC);
CREATE UNIQUE INDEX OPENCOURSE_FACILITY_INX01 ON OPENCOURSE_FACILITY (COURSE_SEQ ASC, FACILITY_SEQ ASC);
CREATE UNIQUE INDEX ORGANIZATION_INX01 ON ORGANIZATION (PARENT_ORGANIZATION_SEQ ASC, ORGANIZATION_SEQ ASC);
CREATE UNIQUE INDEX ORGANIZATION_COURSBANK_INX01 ON ORGANIZATION_COURSEBANK (COURSEBANK_SEQ ASC);
CREATE UNIQUE INDEX ORGANIZATION_COURSBANK_INX02 ON ORGANIZATION_COURSEBANK (COURSEBANK_SEQ ASC);
CREATE INDEX ORGANIZATION_MEMBER_INX01 ON ORGANIZATION_MEMBER (ORGANIZATION_SEQ ASC, MEMBER_SEQ ASC);
CREATE UNIQUE INDEX PROJECT_MEMBER_INX01 ON PROJECT_MEMBER (PROJECT_SEQ ASC, LECTURE_MEMBER_SEQ ASC);
CREATE UNIQUE INDEX PROJECT_MEMBER_INX02 ON PROJECT_MEMBER (LECTURE_MEMBER_SEQ ASC, PROJECT_SEQ ASC);
CREATE UNIQUE INDEX QUESTION_INX01 ON QUESTION (PARENT_QUESTION_SEQ ASC, QUESTION_SEQ ASC);
CREATE UNIQUE INDEX QUESTIONBANK_INX01 ON QUESTIONBANK (PARENT_QUESTIONBANK_SEQ ASC, QUESTIONBANK_SEQ ASC);
CREATE UNIQUE INDEX QUESTION_STANDARDEVALUATION_INX01 ON QUESTION_STANDARDEVALUATION (RELATEDTABLE_SEQ ASC, STANDARDEVALUATION_ID ASC);
CREATE UNIQUE INDEX RELATEDFILE_INX01 ON RELATEDATTACHFILE (RELATEDTABLE_SEQ ASC, ATTACHFILE_SEQ ASC);
CREATE UNIQUE INDEX RELATEDCONTACTMISC_INX01 ON RELATEDCONTACTMISC (RELATEDTABLE_SEQ ASC, CONTACTMISC_SEQ ASC);
CREATE UNIQUE INDEX RELATEDEXCEPTIONTIME_INX01 ON RELATEDEXCEPTEDDATE (RELATEDTABLE_SEQ ASC, EXCEPTEDDATE_SEQ ASC);
CREATE UNIQUE INDEX RELATEDNCSCODE_INX01 ON RELATEDNCSCODE (RELATEDTABLE_SEQ ASC, NCSCODE_SEQ ASC);
CREATE INDEX SENDEDMESSAGE_MEMBER_INX01 ON SENDEDMESSAGE_MEMBER (SENDEDMESSAGE_SEQ ASC);

-- DUMMY(수정전)

Insert into MEMBER 
(MEMBER_SEQ,MEMBER_ID,CRYPT_PASSWORD,NAME,PHONE_NUMBER,TEMPORARY_YN,REGISTRY_DATE) 
select 'TEST-MEMBER-2211111','yojulab01@tistory.com','yojulab','yojulab Manager','010-1234-45678','TEMPORARY_YN_NO',now() from dual union all 
select 'TEST-MEMBER-1111111','system_admin@pulsehu.com','system_admin','system admin','010-1234-45678','TEMPORARY_YN_NO',now() from dual union all 
select 'TEST-MEMBER-1111112','guest@pulsehu.com','guest','system guest','010-1234-45678','TEMPORARY_YN_YES',now() from dual union all 
select 'TEST-MEMBER-1111113','member@pulsehu.com','member','system member','010-1234-45678','TEMPORARY_YN_YES',now() from dual union all 
select 'TEST-MEMBER-1111114','system@pulsehu.com','system','system admin','010-1234-45678','TEMPORARY_YN_YES',now() from dual ; 

-- password = "123456" with BCryptPasswordEncoder() 
update MEMBER
set CRYPT_PASSWORD = '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.'
	, TEMPORARY_YN = 'TEMPORARY_YN_NO';

insert into ORGANIZATION 
(ORGANIZATION_SEQ,NAME,URI,TYPE,TEMPORARY_YN, PARENT_ORGANIZATION_SEQ) 
SELECT 'TEST-ORGANIZATION-YOJULAB01','테스트 업체','http://www.yojulab.com','ORGANIZATION_TYPE_ORGANIZATION', 'TEMPORARY_YN_NO', NULL FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI9401','강사단','http://www.yojulab.com','ORGANIZATION_POSITION_MANAGER', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI7S01','재무부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI8201','지원부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI8S01','홍보부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual 
;

insert into ORGANIZATION_MEMBER 
(ORGANIZATION_MEMBER_SEQ,TYPE,ORGANIZATION_SEQ,MEMBER_SEQ) 
select 'TEST-ORGANIZATION_MEMBER-1111112','ORGANIZATION_POSITION_02','TEST-ORGANIZATION-CIPI9401','TEST-MEMBER-1111112' from dual union all 
select 'TEST-ORGANIZATION_MEMBER-1111113','ORGANIZATION_POSITION_MANAGER','TEST-ORGANIZATION-CIPI8S01','TEST-MEMBER-1111113' from dual union all 
select 'TEST-ORGANIZATION_MEMBER-1111114','ORGANIZATION_POSITION_02','TEST-ORGANIZATION-CIPI8S01','TEST-MEMBER-1111114' from dual ; 

select * from AUTHORITY;
-- 권한 종류
insert into AUTHORITY_MEMBER 
(AUTHORITY_ID,MEMBER_SEQ) 
select 'ROLE_BIZ_MANAGER','TEST-MEMBER-1111114' from dual union all
select 'ROLE_BIZ_LECTURER','TEST-MEMBER-1111114' from dual union all
select 'ROLE_BIZ_MANAGER','TEST-MEMBER-1111113' from dual union all
select 'ROLE_BIZ_LECTURER','TEST-MEMBER-1111113' from dual ;

insert into AUTHORITY_MEMBER 
(AUTHORITY_ID,MEMBER_SEQ)
select 'ROLE_STUDENT',MEMBER_SEQ
from MEMBER
where MEMBER_SEQ like 'TEST-MEMBER-1111%';

delete from COURSE_QUESTION;
delete from QUESTION where PARENT_QUESTION_SEQ is not null; 
delete from QUESTION; 
delete from ORGANIZATION_COURSE;
delete from COURSE where PARENT_COURSE_SEQ is not null;

-- first step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01','쇼핑몰 플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점 무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00',NULL,'UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_02','가이드 라인 통한 아이템 선정 ','판매 제품 선정 따른 어려움 해결 목적.',DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 75 day), '%Y-%m-%d'),'09:00','15:00',NULL,'UUID-ORGANIZATION-YOJULAB' from dual union all 
select 'TEST_T_03','옆구리 찌르는 키워드 잡기 ','소비자 관심 유발하는 제목 만들기 목적.',DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 80 day), '%Y-%m-%d'),'10:00','12:00',NULL,'TEST-ORGANIZATION-YOJULAB01' from dual union all 
select 'TEST_T_04','궁금증 연결 통한 구매 높이기 ','소비자 신뢰 높이기 위한 정보 제공 목적.',DATE_FORMAT(date_add(now(),interval -1 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 65 day), '%Y-%m-%d'),'10:00','16:00',NULL,'TEST-ORGANIZATION-YOJULAB01' from dual; 

insert into ORGANIZATION_COURSE 
(ORGANIZATION_COURSE_SEQ, RECRUIT_START_DATE, RECRUIT_END_DATE, COUNT ,TYPE, USE_YN , COURSE_SEQ) 
select 'TEST_T_01', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'), 25,null,'USE_YN_YES','TEST_T_01' from dual union all
select 'TEST_T_02', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 8 day), '%Y-%m-%d'), 10,null,'USE_YN_YES' , 'TEST_T_02' from dual union all
select 'TEST_T_03', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 8 day), '%Y-%m-%d'), 30,null,'USE_YN_NO' , 'TEST_T_03' from dual union all
select 'TEST_T_04', DATE_FORMAT(date_add(now(),interval -20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval -10 day), '%Y-%m-%d'), 15,null,'USE_YN_YES' , 'TEST_T_04' from dual;

-- second step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01_01','소규모 강의 ','대상 판매 .', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_02','판매 전략 소규모 강의 ','무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 35 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_03','입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 36 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_04','플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 대상 판매 .', DATE_FORMAT(date_add(now(),interval 46 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 55 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_05','쇼핑몰 플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점 무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 56 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual;  

-- third step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01_011','소규모','대상', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 22 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_012','강의 ','판매 .', DATE_FORMAT(date_add(now(),interval 23 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_022','판매 전략 소규모 강의 ','무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 35 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_02','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_033','입점 무역인 판매 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 36 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 40 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_03','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_034','소규모 강의 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 41 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_03','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_044','플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 대상 판매 .', DATE_FORMAT(date_add(now(),interval 46 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 55 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_04','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_055','쇼핑몰 플랫폼 입점','쇼핑몰 플랫폼 입점 무역인', DATE_FORMAT(date_add(now(),interval 56 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 59 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_05','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_056','전략 소규모 강의 ','쇼핑몰 플랫폼 ', DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_05','UUID-ORGANIZATION-YOJULAB' from dual ;  

-- first step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ)
select 'TEST_QUESTION_T_04','QUESTION_TYPE_EXAMINATION', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '01.주간 시험', 10, NULL from dual union all  
select 'TEST_QUESTION_T_03','QUESTION_TYPE_EXAMINATION', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '02.주간 시험', 10, NULL from dual union all  
select 'TEST_QUESTION_T_02','QUESTION_TYPE_NOTICE', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '오리엔테이션 안내 ', 0, NULL from dual union all  
select 'TEST_QUESTION_T_05','QUESTION_TYPE_SURVEY', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '중간 설문 ', 0, NULL from dual union all  
select 'TEST_QUESTION_T_06','QUESTION_TYPE_PROJECT', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '최종 프로젝트 안내 ', 10, NULL from dual union all  
select 'TEST_QUESTION_T_01','QUESTION_TYPE_SURVEY', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '마무리 설문 ', 0, NULL from dual ;  
		
insert into COURSE_QUESTION 
(COURSE_QUESTION_SEQ, START_DATE,END_DATE, COURSE_SEQ, QUESTION_SEQ)
select 'TEST_COURSE_QUESTION_T_14', DATE_FORMAT(date_add(now(),interval 59 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'), 'TEST_T_01_055' , 'TEST_QUESTION_T_04' from dual union all
select 'TEST_COURSE_QUESTION_T_13', DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 50 day), '%Y-%m-%d'), 'TEST_T_01_03' , 'TEST_QUESTION_T_03' from dual union all
select 'TEST_COURSE_QUESTION_T_12', DATE_FORMAT(date_add(now(),interval -5 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval -5 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_02' from dual union all
select 'TEST_COURSE_QUESTION_T_15', DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_05' from dual union all
select 'TEST_COURSE_QUESTION_T_16', DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'), 'TEST_T_01_055' , 'TEST_QUESTION_T_06' from dual union all
select 'TEST_COURSE_QUESTION_T_11', DATE_FORMAT(date_add(now(),interval 61 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 61 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_01' from dual ;

-- second step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ,CONTENT)
select 'TEST_QUESTION_T_041','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 1, '언어가 아닌 것은 ?', 1, 'TEST_QUESTION_T_04', null from dual union all  
select 'TEST_QUESTION_T_042','ANSWER_TYPE_WRITE', null, 1, '기술하시오.', 3, 'TEST_QUESTION_T_04', '기술' from dual union all
select 'TEST_QUESTION_T_031','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 2, '프로그래밍 언어가 아닌 것은 ?', 1, 'TEST_QUESTION_T_03', null from dual union all  
select 'TEST_QUESTION_T_032','ANSWER_TYPE_WRITE', null, 1, '알고리즘 기술하시오.', 3, 'TEST_QUESTION_T_03', '알고리즘' from dual union all
select 'TEST_QUESTION_T_021','ANSWER_TYPE_WRITE', null, 1, '- 오리엔테이션 안내, 장소 : 알림.', 1, 'TEST_QUESTION_T_02', null from dual union all  
select 'TEST_QUESTION_T_056','ANSWER_TYPE_DIVIDE', null, 1, '<시설 관련>', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_051','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE2', 2, '시설 역량은 ?', 1, 'TEST_QUESTION_T_05', null from dual union all  
select 'TEST_QUESTION_T_052','ANSWER_TYPE_WRITE', null, 3, '기관에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_055','ANSWER_TYPE_DIVIDE', null, 4, '<강사 관련>', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_053','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 5, '강사 역량은 ?', 1, 'TEST_QUESTION_T_05', null from dual union all  
select 'TEST_QUESTION_T_054','ANSWER_TYPE_WRITE', null, 6, '강사에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_021','ANSWER_TYPE_WRITE', null, 1, '- 오리엔테이션 안내, 장소 : 알림.', 1, 'TEST_QUESTION_T_02', null from dual union all  
select 'TEST_QUESTION_T_061','ANSWER_TYPE_WRITE', null, 1, '- 프로젝트 진행 요령', 1, 'TEST_QUESTION_T_06', null from dual union all  
select 'TEST_QUESTION_T_012','ANSWER_TYPE_WRITE', null, 2, '강사에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_01', null from dual;  

-- third step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ)
select 'TEST_QUESTION_T_0415', NULL, NULL, 5, 'node.js', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0414', NULL, NULL, 4, 'C++', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0413', NULL, NULL, 3, 'Dart', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0412', NULL, NULL, 2, 'Java', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0411', NULL, NULL, 1, 'Korea', 1, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0315', NULL, NULL, 5, 'node.js', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0314', NULL, NULL, 4, 'English', 1, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0313', NULL, NULL, 3, 'Dart', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0312', NULL, NULL, 2, 'Java', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0311', NULL, NULL, 1, 'Korea', 1, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0511', NULL, NULL, 1, '만족', 3, 'TEST_QUESTION_T_051' from dual union all  
select 'TEST_QUESTION_T_0512', NULL, NULL, 2, '불만족', 1, 'TEST_QUESTION_T_051' from dual union all 
select 'TEST_QUESTION_T_0531', NULL, NULL, 1, '매우 불만족', 1, 'TEST_QUESTION_T_053' from dual union all 
select 'TEST_QUESTION_T_0532', NULL, NULL, 2, '불만족', 2, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0533', NULL, NULL, 3, '중간', 3, 'TEST_QUESTION_T_053' from dual union all 
select 'TEST_QUESTION_T_0534', NULL, NULL, 4, '만족', 4, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0535', NULL, NULL, 5, '매우 만족', 5, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0111', NULL, NULL, 1, '만족', 3, 'TEST_QUESTION_T_011' from dual union all  
select 'TEST_QUESTION_T_0112', NULL, NULL, 2, '불만족', 1, 'TEST_QUESTION_T_011' from dual ; 

insert into yojulabdb.MULTIBOARDGROUP
(RELATEDTABLE_SEQ, MULTI_BOARDGROUP_ID, NAME, TYPE, CONTENT, ORDER_NUMBER, USE_YN)
select 'TEST_BOARDGROUP_ID_01', 'TEST_BOARDGROUP_ID_01', '테스트 멀티 보드 01', 'BOARD_TYPE_NOTICE', '테스트 멀티 보드 01', 1, 'USE_YN_YES' from dual union all 
select 'TEST_BOARDGROUP_ID_02', 'TEST_BOARDGROUP_ID_02', '테스트 멀티 보드 02', 'BOARD_TYPE_NOTICE', '테스트 멀티 보드 02', 2, 'USE_YN_YES' from dual ;

insert into yojulabdb.MULTIBOARD
(MULTIBOARD_SEQ, TITLE, CONTENT, START_DATE, END_DATE, CRYPT_PASSWORD, USE_YN, MEMBER_SEQ, REGISTRY_DATE, MODIFY_DATE, PARENT_MULTIBOARD_SEQ, MULTI_BOARDGROUP_ID)
select 'TEST_BOARD_ID_011', ' 테스트 011',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'UUID-MEMBER-2111111', date_add(now(),interval -10 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_012', ' 테스트 012',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111111', date_add(now(),interval -4 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_013', ' 테스트 013',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -3 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_014', ' 테스트 014',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111113', date_add(now(),interval -2 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_015', ' 테스트 015',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -1 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_016', ' 테스트 016',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -9 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_017', ' 테스트 017',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111111', date_add(now(),interval 0 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_021', ' 테스트 021',  ' 테스트 021', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-2111111', date_add(now(),interval 0 day),now() , NULL, 'TEST_BOARDGROUP_ID_02' from dual ;

-- INSERT RECORDS TO TABLES

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'ORGANIZATION_TYPE','기관/협회/학원/조직 유형',1,'기관/협회/학원/조직 유형 적용','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'ORGANIZATION_TYPE_LECTURE','강사',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_TYPE' from dual union all 
select 'ORGANIZATION_TYPE_ORGANIZATION','기관/협회',2,'조직 적용 ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_TYPE' from dual union all 
select 'ORGANIZATION_TYPE_ACADEMY','학원',2,'조직 적용 ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_TYPE' from dual union all 
select 'ORGANIZATION_POSITION','조직근무자 유형',1,'Using Yes or No','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'ORGANIZATION_POSITION_POSTION','역활',2,'역활 적용 ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_POSITION' from dual union all 
select 'ORGANIZATION_POSITION_MANAGER','대표 담당자',1,'대표 담당자 적용 ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_POSITION' from dual union all 
select 'ORGANIZATION_POSITION_LECTURE','정규직 강사',1,'상사 적용 ','SYSTEM_CODE_YN_YES','USE_YN_YES','ORGANIZATION_POSITION' from dual union all 
select 'USE_YN','Using Yes or No',1,'Using Yes or No','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'USE_YN_YES','Yes',1,'Using Yes','SYSTEM_CODE_YN_YES','USE_YN_YES','USE_YN' from dual union all 
select 'USE_YN_NO','No',2,'Using No','SYSTEM_CODE_YN_YES','USE_YN_YES','USE_YN' from dual union all 
select 'TEMPORARY_YN','Using Yes or No',1,'Using Yes or No','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'TEMPORARY_YN_YES','Yes',1,'Using Yes','SYSTEM_CODE_YN_YES','USE_YN_YES','TEMPORARY_YN' from dual union all 
select 'TEMPORARY_YN_NO','No',2,'Using No','SYSTEM_CODE_YN_YES','USE_YN_YES','TEMPORARY_YN' from dual union all 
select 'SYSTEM_CODE_YN','Sytem Yes or No',1,'Sytem Using Yes or No','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'SYSTEM_CODE_YN_YES','Yes',1,'Sytem Using Yes','SYSTEM_CODE_YN_YES','USE_YN_YES','SYSTEM_CODE_YN' from dual union all 
select 'SYSTEM_CODE_YN_NO','No',2,'Sytem Using No','SYSTEM_CODE_YN_YES','USE_YN_YES','SYSTEM_CODE_YN' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'QUESTION_TYPE','질문지 유형 ',1,'질문지 유형 ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'QUESTION_TYPE_NOTICE','안내 ',1,'안내 ','SYSTEM_CODE_YN_YES','USE_YN_YES','QUESTION_TYPE' from dual union all 
select 'QUESTION_TYPE_SURVEY','설문 ',2,'설문지 ','SYSTEM_CODE_YN_YES','USE_YN_YES','QUESTION_TYPE' from dual union all 
select 'QUESTION_TYPE_PROJECT','프로젝트 ',4,'설문지 ','SYSTEM_CODE_YN_YES','USE_YN_YES','QUESTION_TYPE' from dual union all 
select 'QUESTION_TYPE_EXAMINATION','문답 ',3,'문답하기 ','SYSTEM_CODE_YN_YES','USE_YN_YES','QUESTION_TYPE' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'MESSAGE_KIND','메세지 유형 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'MESSAGE_KIND_EMAIL','이메일 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','MESSAGE_KIND' from dual union all 
select 'MESSAGE_KIND_SMS','SMS ',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','MESSAGE_KIND' from dual union all 
select 'MESSAGE_KIND_KAKAOTALK','카카오톡 ',3,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','MESSAGE_KIND' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'ANSWER_TYPE','답변 유형 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'ANSWER_TYPE_WRITE','쓰기 방식 ',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','ANSWER_TYPE' from dual union all 
select 'ANSWER_TYPE_CHOICE','고르기 방식 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','ANSWER_TYPE' from dual union all 
select 'ANSWER_TYPE_DIVIDE','질문간 나누기',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','ANSWER_TYPE' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'ANSWER_TYPE_CHOICE_TYPE','선택식 답변 문제 형성 유형 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE5','5 형식',5,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','ANSWER_TYPE_CHOICE_TYPE' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE2','2 형식',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','ANSWER_TYPE_CHOICE_TYPE' from dual union all 
select 'STANDARD_ANSWER_CHOICE_WRITE','직접 작성 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','ANSWER_TYPE_CHOICE_TYPE' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'LECTURE_ATTEND_TYPE','강의 참석자 유형(수강생, 강사 등) ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'LECTURE_ATTEND_TYPE_LISTENER','수강생',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_TYPE' from dual union all 
select 'LECTURE_ATTEND_TYPE_LECTURER','강사',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_TYPE' from dual union all 
select 'LECTURE_ATTEND_TYPE_MENAGER','관리자',3,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','LECTURE_ATTEND_TYPE' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'LECTURE_ATTEND_KIND','지원,불합격,합격,수료 종류 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'LECTURE_ATTEND_KIND_APPLY','지원 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_KIND' from dual union all 
select 'LECTURE_ATTEND_KIND_WAITING','대기 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_KIND' from dual union all 
select 'LECTURE_ATTEND_KIND_PASS','합격 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_KIND' from dual union all 
select 'LECTURE_ATTEND_KIND_FAIL','불합격 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_KIND' from dual union all 
select 'LECTURE_ATTEND_KIND_CANSEL','자진탈퇴 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','LECTURE_ATTEND_KIND' from dual union all 
select 'LECTURE_ATTEND_KIND_COMPLETION','수료 ',2,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','LECTURE_ATTEND_KIND' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'AFTER_LECTURE_STATUS_TYPE','강의 참석자 업무 유형(수강생, 강사 등) ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'AFTER_LECTURE_STATUS_TYPE_LISTENER','준비',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','AFTER_LECTURE_STATUS_TYPE' from dual union all 
select 'AFTER_LECTURE_STATUS_TYPE_LECTURE','취업 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','AFTER_LECTURE_STATUS_TYPE' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,ORDER_NUMBER,CONTENT,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'MESSAGEGROUP_DEFAULT_CATEGORY','메세지 그룹 초기화 카테고리',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES',NULL from dual union all 
select 'MESSAGEGROUP_DEFAULT_CATEGORY_TOTAL','전체 ',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_YES','MESSAGEGROUP_DEFAULT_CATEGORY' from dual union all 
select 'MESSAGEGROUP_DEFAULT_CATEGORY_COURSE','개설 과정들',1,'시스템 입력  ','SYSTEM_CODE_YN_YES','USE_YN_NO','MESSAGEGROUP_DEFAULT_CATEGORY' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,COUNT,ORDER_NUMBER,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'STANDARD_ANSWER_CHOICE_TYPE5_5','매우만족 ',5,1,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE5' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE5_4','만족 ',4,2,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE5' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE5_3','보통 ',3,3,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE5' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE5_2','불만족 ',2,4,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE5' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE5_1','매우불만족 ',1,5,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE5' from dual
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,COUNT,ORDER_NUMBER,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'STANDARD_ANSWER_CHOICE_TYPE2_5','만족 ',5,1,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE2' from dual union all 
select 'STANDARD_ANSWER_CHOICE_TYPE2_1','불만족 ',1,2,'SYSTEM_CODE_YN_YES','USE_YN_YES','STANDARD_ANSWER_CHOICE_TYPE2' from dual 
; 

insert into COMMONCODE 
(COMMONCODE_ID,NAME,COUNT,ORDER_NUMBER,SYSTEM_CODE_YN,USE_YN,PARENT_COMMONCODE_ID) 
select 'PICKUP_WAY','청강생 선출 방식', 0,1,'SYSTEM_CODE_YN_YES','USE_YN_YES',null from dual union all 
select 'PICKUP_WAY_FIRSTCOME','선착순', 0,1,'SYSTEM_CODE_YN_YES','USE_YN_YES','PICKUP_WAY' from dual union all 
select 'PICKUP_WAY_INTERVIEW','면접 후 승인', 0,1,'SYSTEM_CODE_YN_YES','USE_YN_YES','PICKUP_WAY' from dual 
; 

insert into ORGANIZATION 
(ORGANIZATION_SEQ,NAME,URI,TYPE,TEMPORARY_YN, PARENT_ORGANIZATION_SEQ) 
SELECT 'UUID-ORGANIZATION-YOJULAB','강의/강연 신','http://www.yojulab.com','ORGANIZATION_TYPE_ORGANIZATION', 'TEMPORARY_YN_NO', NULL FROM dual UNION ALL
SELECT 'UUID-ORGANIZATION-CIPI94','강사단','http://www.yojulab.com','ORGANIZATION_POSITION_MANAGER', 'TEMPORARY_YN_NO', 'UUID-ORGANIZATION-YOJULAB' FROM dual UNION ALL
SELECT 'UUID-ORGANIZATION-CIPI7S','재무부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'UUID-ORGANIZATION-YOJULAB' FROM dual UNION ALL
SELECT 'UUID-ORGANIZATION-CIPI82','지원부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'UUID-ORGANIZATION-YOJULAB' FROM dual UNION ALL
SELECT 'UUID-ORGANIZATION-CIPI8S','홍보부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'UUID-ORGANIZATION-YOJULAB' FROM dual 
;


DELETE FROM MENU_AUTHORITY;
DELETE FROM MENU;

DELETE FROM AUTHORITY_MEMBER;
DELETE FROM AUTHORITY;

-- 권한 종류
insert into AUTHORITY 
(AUTHORITY_ID,NAME) 
select 'ROLE_SYSTEM_ADMIN','SYSTEM ADMIN' from dual union all
select 'ROLE_SYSTEM_MANAGER','SYSTEM MANAGER' from dual union all
select 'ROLE_BIZ_ADMIN','BIZ ADMIN' from dual union all
select 'ROLE_BIZ_MANAGER','BIZ MANAGER' from dual union all
select 'ROLE_BIZ_LECTURER','BIZ LECTURER' from dual union all
select 'ROLE_STUDENT','STUDENT' from dual ;


DELETE FROM AUTHORITY_MEMBER;

delete from MEMBER;

insert into MEMBER 
(MEMBER_SEQ,MEMBER_ID,CRYPT_PASSWORD,NAME,PHONE_NUMBER,TEMPORARY_YN,REGISTRY_DATE) 
select 'UUID-MEMBER-2111111','yojulab@tistory.com','yojulab','yojulab Admin','010-1234-45678','TEMPORARY_YN_NO',now() from dual ; 

-- password = "123456" with BCryptPasswordEncoder() 
update MEMBER
set CRYPT_PASSWORD = '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.'
	, TEMPORARY_YN = 'TEMPORARY_YN_NO';

insert into ORGANIZATION_MEMBER 
(ORGANIZATION_MEMBER_SEQ,TYPE,ORGANIZATION_SEQ,MEMBER_SEQ) 
select 'UUID-ORGANIZATION_MEMBER-2111111','ORGANIZATION_POSITION_MANAGER','UUID-ORGANIZATION-YOJULAB','UUID-MEMBER-2111111' from dual; 

DELETE FROM AUTHORITY_MEMBER;

select * from AUTHORITY;
-- 권한 종류
insert into AUTHORITY_MEMBER 
(AUTHORITY_ID,MEMBER_SEQ) 
select 'ROLE_SYSTEM_MANAGER','UUID-MEMBER-2111111' from dual union all
select 'ROLE_BIZ_ADMIN','UUID-MEMBER-2111111' from dual union all
select 'ROLE_BIZ_MANAGER','UUID-MEMBER-2111111' from dual union all
select 'ROLE_BIZ_LECTURER','UUID-MEMBER-2111111' from dual union all
select 'ROLE_STUDENT','UUID-MEMBER-2111111' from dual ;

delete from MENU_AUTHORITY;
delete from MENU;

-- 메뉴
insert into MENU
(MENU_ID,NAME,USE_YN,PARENT_MENU_ID)
select '/security/insert','로그인폼','USE_YN',NULL from dual union all 
select '/member/list','/member/list','USE_YN',NULL from dual union all 
select '/member/edit','/member/list','USE_YN',NULL from dual union all 
select '/project/list','/project/list','USE_YN',NULL from dual union all 
select '/project/edit','/project/edit','USE_YN',NULL from dual union all 
select '/project/read','/project/read','USE_YN',NULL from dual union all 
select '/project/delete','/project/delete','USE_YN',NULL from dual union all 
select '/project/modify','/project/modify','USE_YN',NULL from dual ;

insert into MENU_AUTHORITY
(MENU_AUTHORITY_SEQ, MENU_ID, AUTHORITY_ID)
select 'MENU_AUTHORITY-01', '/member/list','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-02', '/member/edit','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-03', '/project/list','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-04', '/project/edit','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-05', '/project/read','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-06', '/project/modify','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-07', '/project/delete','ROLE_BIZ_ADMIN' from dual union all 
select 'MENU_AUTHORITY-08', '/project/list','ROLE_SYSTEM_MANAGER' from dual ;


insert into MESSAGEFORM
(MESSAGEFORM_ID, TYPE, KIND, TITLE, CONTENT, SYSTEM_CODE_YN)
select 'AUTHORITY_SIGNUP_TEMPORARY_MESSAGE', 'QUESTION_TYPE_NOTICE','MESSAGE_KIND_EMAIL', '{{NAME}}님. 회원가입 승인 메일', '{{NAME}}님. 완전한 가입 위해선 주소를 클릭하세요. http://localhost:8081/project_yojulab/security/update?MEMBER_SEQ={{MEMBER_SEQ}}', 'SYSTEM_CODE_YN_YES' from dual ;

-- 수정 전 데이터 삭제

DELETE FROM MEMBER;
DELETE FROM ORGANIZATION;
DELETE FROM ORGANIZATION_MEMBER;
DELETE FROM AUTHORITY_MEMBER;
DELETE FROM COURSE;
DELETE FROM QUESTION;
DELETE FROM COURSE_QUESTION;
DELETE FROM yojulab.MULTIBOARD;
DELETE FROM yojulab.MULTIBOARDGROUP;

-- DUMMY 데이터 (수정후) 

insert into MEMBER 
(MEMBER_SEQ,MEMBER_ID,CRYPT_PASSWORD,NAME,PHONE_NUMBER,TEMPORARY_YN,REGISTRY_DATE) 
select 'TEST-MEMBER-2211111','yojulab01@tistory.com','yojulab','yojulab Manager','010-1234-45678','TEMPORARY_YN_NO',now() from dual union all 
select 'TEST-MEMBER-1111111','system_admin@pulsehu.com','system_admin','system admin','010-1234-45678','TEMPORARY_YN_NO',now() from dual union all 
select 'TEST-MEMBER-1111112','guest@pulsehu.com','guest','system guest','010-1234-45678','TEMPORARY_YN_YES',now() from dual union all 
select 'TEST-MEMBER-1111113','member@pulsehu.com','member','system member','010-1234-45678','TEMPORARY_YN_YES',now() from dual union all 
select 'TEST-MEMBER-1111114','system@pulsehu.com','system','system admin','010-1234-45678','TEMPORARY_YN_YES',now() from dual ; 

-- password = "123456" with BCryptPasswordEncoder() 
update MEMBER
set CRYPT_PASSWORD = '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.'
	, TEMPORARY_YN = 'TEMPORARY_YN_NO';

insert into ORGANIZATION 
(ORGANIZATION_SEQ,NAME,URI,TYPE,TEMPORARY_YN, PARENT_ORGANIZATION_SEQ) 
SELECT 'TEST-ORGANIZATION-YOJULAB01','테스트 업체','http://www.yojulab.com','ORGANIZATION_TYPE_ORGANIZATION', 'TEMPORARY_YN_NO', NULL FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI9401','강사단','http://www.yojulab.com','ORGANIZATION_POSITION_MANAGER', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI7S01','재무부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI8201','지원부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual UNION ALL
SELECT 'TEST-ORGANIZATION-CIPI8S01','홍보부','http://www.yojulab.com','ORGANIZATION_POSITION_POSTION', 'TEMPORARY_YN_NO', 'TEST-ORGANIZATION-YOJULAB01' FROM dual 
;

insert into ORGANIZATION_MEMBER 
(ORGANIZATION_MEMBER_SEQ,TYPE,ORGANIZATION_SEQ,MEMBER_SEQ) 
select 'TEST-ORGANIZATION_MEMBER-1111112','ORGANIZATION_POSITION_02','TEST-ORGANIZATION-CIPI9401','TEST-MEMBER-1111112' from dual union all 
select 'TEST-ORGANIZATION_MEMBER-1111113','ORGANIZATION_POSITION_MANAGER','TEST-ORGANIZATION-CIPI8S01','TEST-MEMBER-1111113' from dual union all 
select 'TEST-ORGANIZATION_MEMBER-1111114','ORGANIZATION_POSITION_02','TEST-ORGANIZATION-CIPI8S01','TEST-MEMBER-1111114' from dual ; 

select * from AUTHORITY;
-- 권한 종류
insert into AUTHORITY_MEMBER 
(AUTHORITY_ID,MEMBER_SEQ) 
select 'ROLE_BIZ_MANAGER','TEST-MEMBER-1111114' from dual union all
select 'ROLE_BIZ_LECTURER','TEST-MEMBER-1111114' from dual union all
select 'ROLE_BIZ_MANAGER','TEST-MEMBER-1111113' from dual union all
select 'ROLE_BIZ_LECTURER','TEST-MEMBER-1111113' from dual ;

insert into AUTHORITY_MEMBER 
(AUTHORITY_ID,MEMBER_SEQ)
select 'ROLE_STUDENT',MEMBER_SEQ
from MEMBER
where MEMBER_SEQ like 'TEST-MEMBER-1111%';

delete from COURSE_QUESTION;
delete from QUESTION where PARENT_QUESTION_SEQ is not null; 
delete from QUESTION; 
delete from ORGANIZATION_COURSE;
delete from COURSE where PARENT_COURSE_SEQ is not null;

-- first step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01','쇼핑몰 플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점 무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00',NULL,'UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_02','가이드 라인 통한 아이템 선정 ','판매 제품 선정 따른 어려움 해결 목적.',DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 75 day), '%Y-%m-%d'),'09:00','15:00',NULL,'UUID-ORGANIZATION-YOJULAB' from dual union all 
select 'TEST_T_03','옆구리 찌르는 키워드 잡기 ','소비자 관심 유발하는 제목 만들기 목적.',DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 80 day), '%Y-%m-%d'),'10:00','12:00',NULL,'TEST-ORGANIZATION-YOJULAB01' from dual union all 
select 'TEST_T_04','궁금증 연결 통한 구매 높이기 ','소비자 신뢰 높이기 위한 정보 제공 목적.',DATE_FORMAT(date_add(now(),interval -1 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 65 day), '%Y-%m-%d'),'10:00','16:00',NULL,'TEST-ORGANIZATION-YOJULAB01' from dual; 

insert into ORGANIZATION_COURSE 
(ORGANIZATION_COURSE_SEQ, RECRUIT_START_DATE, RECRUIT_END_DATE, COUNT ,TYPE, USE_YN , COURSE_SEQ) 
select 'TEST_T_01', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'), 25,null,'USE_YN_YES','TEST_T_01' from dual union all
select 'TEST_T_02', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 8 day), '%Y-%m-%d'), 10,null,'USE_YN_YES' , 'TEST_T_02' from dual union all
select 'TEST_T_03', DATE_FORMAT(date_add(now(),interval 0 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 8 day), '%Y-%m-%d'), 30,null,'USE_YN_NO' , 'TEST_T_03' from dual union all
select 'TEST_T_04', DATE_FORMAT(date_add(now(),interval -20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval -10 day), '%Y-%m-%d'), 15,null,'USE_YN_YES' , 'TEST_T_04' from dual;

-- second step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01_01','소규모 강의 ','대상 판매 .', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_02','판매 전략 소규모 강의 ','무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 35 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_03','입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 36 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_04','플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 대상 판매 .', DATE_FORMAT(date_add(now(),interval 46 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 55 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_05','쇼핑몰 플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 플랫폼 입점 무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 56 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01','UUID-ORGANIZATION-YOJULAB' from dual;  

-- third step
insert into COURSE 
(COURSE_SEQ, TITLE, CONTENT, START_DATE, END_DATE, START_TIME, END_TIME, PARENT_COURSE_SEQ ,ORGANIZATION_SEQ) 
select 'TEST_T_01_011','소규모','대상', DATE_FORMAT(date_add(now(),interval 20 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 22 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_012','강의 ','판매 .', DATE_FORMAT(date_add(now(),interval 23 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_01','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_022','판매 전략 소규모 강의 ','무역인 대상 판매 .', DATE_FORMAT(date_add(now(),interval 25 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 35 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_02','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_033','입점 무역인 판매 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 36 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 40 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_03','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_034','소규모 강의 ','쇼핑몰 플랫폼 입점', DATE_FORMAT(date_add(now(),interval 41 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_03','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_044','플랫폼 입점 무역인 판매 전략 소규모 강의 ','쇼핑몰 대상 판매 .', DATE_FORMAT(date_add(now(),interval 46 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 55 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_04','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_055','쇼핑몰 플랫폼 입점','쇼핑몰 플랫폼 입점 무역인', DATE_FORMAT(date_add(now(),interval 56 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 59 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_05','UUID-ORGANIZATION-YOJULAB' from dual union all  
select 'TEST_T_01_056','전략 소규모 강의 ','쇼핑몰 플랫폼 ', DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'),'09:00','18:00','TEST_T_01_05','UUID-ORGANIZATION-YOJULAB' from dual ;  

-- first step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ)
select 'TEST_QUESTION_T_04','QUESTION_TYPE_EXAMINATION', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '01.주간 시험', 10, NULL from dual union all  
select 'TEST_QUESTION_T_03','QUESTION_TYPE_EXAMINATION', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '02.주간 시험', 10, NULL from dual union all  
select 'TEST_QUESTION_T_02','QUESTION_TYPE_NOTICE', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '오리엔테이션 안내 ', 0, NULL from dual union all  
select 'TEST_QUESTION_T_05','QUESTION_TYPE_SURVEY', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '중간 설문 ', 0, NULL from dual union all  
select 'TEST_QUESTION_T_06','QUESTION_TYPE_PROJECT', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '최종 프로젝트 안내 ', 10, NULL from dual union all  
select 'TEST_QUESTION_T_01','QUESTION_TYPE_SURVEY', 'LECTURE_ATTEND_TYPE_LISTENER', 1, '마무리 설문 ', 0, NULL from dual ;  
		
insert into COURSE_QUESTION 
(COURSE_QUESTION_SEQ, START_DATE,END_DATE, COURSE_SEQ, QUESTION_SEQ)
select 'TEST_COURSE_QUESTION_T_14', DATE_FORMAT(date_add(now(),interval 59 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'), 'TEST_T_01_055' , 'TEST_QUESTION_T_04' from dual union all
select 'TEST_COURSE_QUESTION_T_13', DATE_FORMAT(date_add(now(),interval 45 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 50 day), '%Y-%m-%d'), 'TEST_T_01_03' , 'TEST_QUESTION_T_03' from dual union all
select 'TEST_COURSE_QUESTION_T_12', DATE_FORMAT(date_add(now(),interval -5 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval -5 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_02' from dual union all
select 'TEST_COURSE_QUESTION_T_15', DATE_FORMAT(date_add(now(),interval 10 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_05' from dual union all
select 'TEST_COURSE_QUESTION_T_16', DATE_FORMAT(date_add(now(),interval 15 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 60 day), '%Y-%m-%d'), 'TEST_T_01_055' , 'TEST_QUESTION_T_06' from dual union all
select 'TEST_COURSE_QUESTION_T_11', DATE_FORMAT(date_add(now(),interval 61 day), '%Y-%m-%d'),DATE_FORMAT(date_add(now(),interval 61 day), '%Y-%m-%d'), 'TEST_T_01' , 'TEST_QUESTION_T_01' from dual ;

-- second step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ,CONTENT)
select 'TEST_QUESTION_T_041','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 1, '언어가 아닌 것은 ?', 1, 'TEST_QUESTION_T_04', null from dual union all  
select 'TEST_QUESTION_T_042','ANSWER_TYPE_WRITE', null, 1, '기술하시오.', 3, 'TEST_QUESTION_T_04', '기술' from dual union all
select 'TEST_QUESTION_T_031','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 2, '프로그래밍 언어가 아닌 것은 ?', 1, 'TEST_QUESTION_T_03', null from dual union all  
select 'TEST_QUESTION_T_032','ANSWER_TYPE_WRITE', null, 1, '알고리즘 기술하시오.', 3, 'TEST_QUESTION_T_03', '알고리즘' from dual union all
select 'TEST_QUESTION_T_021','ANSWER_TYPE_WRITE', null, 1, '- 오리엔테이션 안내, 장소 : 알림.', 1, 'TEST_QUESTION_T_02', null from dual union all  
select 'TEST_QUESTION_T_056','ANSWER_TYPE_DIVIDE', null, 1, '<시설 관련>', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_051','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE2', 2, '시설 역량은 ?', 1, 'TEST_QUESTION_T_05', null from dual union all  
select 'TEST_QUESTION_T_052','ANSWER_TYPE_WRITE', null, 3, '기관에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_055','ANSWER_TYPE_DIVIDE', null, 4, '<강사 관련>', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_053','ANSWER_TYPE_CHOICE', 'STANDARD_ANSWER_CHOICE_TYPE5', 5, '강사 역량은 ?', 1, 'TEST_QUESTION_T_05', null from dual union all  
select 'TEST_QUESTION_T_054','ANSWER_TYPE_WRITE', null, 6, '강사에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_05', null from dual union all
select 'TEST_QUESTION_T_060','ANSWER_TYPE_WRITE', null, 1, '- 프로젝트 안내, 장소 : 알림.', 1, 'TEST_QUESTION_T_06', null from dual union all  
select 'TEST_QUESTION_T_061','ANSWER_TYPE_WRITE', null, 1, '- 프로젝트 진행 요령', 1, 'TEST_QUESTION_T_06', null from dual union all  
select 'TEST_QUESTION_T_012','ANSWER_TYPE_WRITE', null, 2, '강사에 하고 싶은 말은 !', 1, 'TEST_QUESTION_T_01', null from dual;  

-- third step
insert into QUESTION 
(QUESTION_SEQ, TYPE, KIND, ORDER_NUMBER, TITLE, WEIGHT, PARENT_QUESTION_SEQ)
select 'TEST_QUESTION_T_0415', NULL, NULL, 5, 'node.js', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0414', NULL, NULL, 4, 'C++', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0413', NULL, NULL, 3, 'Dart', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0412', NULL, NULL, 2, 'Java', 0, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0411', NULL, NULL, 1, 'Korea', 1, 'TEST_QUESTION_T_041' from dual union all  
select 'TEST_QUESTION_T_0315', NULL, NULL, 5, 'node.js', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0314', NULL, NULL, 4, 'English', 1, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0313', NULL, NULL, 3, 'Dart', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0312', NULL, NULL, 2, 'Java', 0, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0311', NULL, NULL, 1, 'Korea', 1, 'TEST_QUESTION_T_031' from dual union all  
select 'TEST_QUESTION_T_0511', NULL, NULL, 1, '만족', 3, 'TEST_QUESTION_T_051' from dual union all  
select 'TEST_QUESTION_T_0512', NULL, NULL, 2, '불만족', 1, 'TEST_QUESTION_T_051' from dual union all 
select 'TEST_QUESTION_T_0531', NULL, NULL, 1, '매우 불만족', 1, 'TEST_QUESTION_T_053' from dual union all 
select 'TEST_QUESTION_T_0532', NULL, NULL, 2, '불만족', 2, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0533', NULL, NULL, 3, '중간', 3, 'TEST_QUESTION_T_053' from dual union all 
select 'TEST_QUESTION_T_0534', NULL, NULL, 4, '만족', 4, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0535', NULL, NULL, 5, '매우 만족', 5, 'TEST_QUESTION_T_053' from dual union all  
select 'TEST_QUESTION_T_0111', NULL, NULL, 1, '만족', 3, 'TEST_QUESTION_T_011' from dual union all  
select 'TEST_QUESTION_T_0112', NULL, NULL, 2, '불만족', 1, 'TEST_QUESTION_T_011' from dual ; 

insert into yojulabdb.MULTIBOARDGROUP
(RELATEDTABLE_SEQ, MULTI_BOARDGROUP_ID, NAME, TYPE, CONTENT, ORDER_NUMBER, USE_YN)
select 'TEST_BOARDGROUP_ID_01', 'TEST_BOARDGROUP_ID_01', '테스트 멀티 보드 01', 'BOARD_TYPE_NOTICE', '테스트 멀티 보드 01', 1, 'USE_YN_YES' from dual union all 
select 'TEST_BOARDGROUP_ID_02', 'TEST_BOARDGROUP_ID_02', '테스트 멀티 보드 02', 'BOARD_TYPE_NOTICE', '테스트 멀티 보드 02', 2, 'USE_YN_YES' from dual ;

insert into yojulabdb.MULTIBOARD
(MULTIBOARD_SEQ, TITLE, CONTENT, START_DATE, END_DATE, CRYPT_PASSWORD, USE_YN, MEMBER_SEQ, REGISTRY_DATE, MODIFY_DATE, PARENT_MULTIBOARD_SEQ, MULTI_BOARDGROUP_ID)
select 'TEST_BOARD_ID_011', ' 테스트 011',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'UUID-MEMBER-2111111', date_add(now(),interval -10 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_012', ' 테스트 012',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111111', date_add(now(),interval -4 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_013', ' 테스트 013',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -3 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_014', ' 테스트 014',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111113', date_add(now(),interval -2 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_015', ' 테스트 015',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -1 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_016', ' 테스트 016',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111114', date_add(now(),interval -9 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_017', ' 테스트 017',  ' 테스트 011', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-1111111', date_add(now(),interval 0 day),now() , NULL, 'TEST_BOARDGROUP_ID_01' from dual union all 
select 'TEST_BOARD_ID_021', ' 테스트 021',  ' 테스트 021', NULL, NULL, NULL, 'USE_YN_YES', 'TEST-MEMBER-2111111', date_add(now(),interval 0 day),now() , NULL, 'TEST_BOARDGROUP_ID_02' from dual ;

SELECT * FROM AUTHORITY;
SELECT * FROM ORGANIZATION;
SELECT * FROM ORGANIZATION_COURSE;
SELECT * FROM yojulabdb.MULTIBOARD;
SELECT * FROM ORGANIZATION_MEMBER;
SELECT * FROM QUESTION;
SELECT * FROM COURSE;
SELECT * FROM MEMBER;
SELECT MEMBER_SEQ FROM AUTHORITY_MEMBER WHERE AUTHORITY_ID='ROLE_STUDENT'; 


-- 1
SELECT MEMBER.MEMBER_SEQ, MEMBER.MEMBER_ID, MEMBER.NAME, AUTHORITY_MEMBER.AUTHORITY_ID 
FROM MEMBER INNER JOIN AUTHORITY_MEMBER ON AUTHORITY_MEMBER.MEMBER_SEQ=MEMBER.MEMBER_SEQ
    INNER JOIN AUTHORITY ON AUTHORITY_MEMBER.AUTHORITY_ID=AUTHORITY.AUTHORITY_ID
    WHERE AUTHORITY.AUTHORITY_ID='ROLE_STUDENT'


-- 2
SELECT * FROM ORGANIZATION;
WITH

SELECT ORGANIZATION_SEQ, NAME, 


-- 3
SELECT * FROM ORGANIZATION_MEMBER;
SELECT * FROM AUTHORITY_MEMBER;
SELECT * FROM ORGANIZATION;
SELECT * FROM COURSE;
