-- SQLite
CREATE TABLE AUTHORITY
(
  AUTH_ID   FLOAT NOT NULL,
  AUTH_NAME TEXT  NULL    ,
  PRIMARY KEY (AUTH_ID)
);

CREATE TABLE MEMBER
(
  ID_EMAIL TEXT  NOT NULL,
  PASSWORD  TEXT  NULL    ,
  NAME      TEXT  NULL    ,
  BIRTHDATE FLOAT NULL    ,
  ADDRESS   TEXT  NULL    ,
  ORG_ID    FLOAT NOT NULL,
  PRIMARY KEY (ID_EMAIL),
  CONSTRAINT FK_ORGANIZATION_TO_MEMBER
    FOREIGN KEY (ORG_ID)
    REFERENCES ORGANIZATION (ORG_ID)
);

CREATE TABLE MEMBER_AUTHORITY
(
  ID_EMAIL TEXT  NOT NULL,
  AUTH_ID   FLOAT NOT NULL,
CONSTRAINT FK_MEMBER_TO_MEMBER_AUTHORITY
    FOREIGN KEY (ID_EMAIL)
    REFERENCES MEMBER (ID_EMAIL),
CONSTRAINT FK_AUTHORITY_TO_MEMBER_AUTHORITY
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTHORITY (AUTH_ID)
);

CREATE TABLE ORGANIZATION
(
  ORG_ID     FLOAT NOT NULL,
  ORG_NAME   TEXT  NULL    ,
  TEL_NO    FLOAT NULL    ,
  MANAGER_ID TEXT  NULL    ,
  PRIMARY KEY (ORG_ID)
);


CREATE TABLE ATTACHFILE
(
  FILE_ID   TEXT  NOT NULL,
  FILE_NAME TEXT  NULL    ,
  FILE_SIZE FLOAT NULL    ,
  FILE_TYPE TEXT  NULL    ,
  ID_EMAIL  TEXT  NOT NULL,
  PRIMARY KEY (FILE_ID),
CONSTRAINT FK_MEMBER_TO_ATTACHFILE
    FOREIGN KEY (ID_EMAIL)
    REFERENCES MEMBER (ID_EMAIL)
);



CREATE TABLE HOBBY
(
  HOBBY_ID TEXT NOT NULL,
  HOBBY    TEXT NULL    ,
  PRIMARY KEY (HOBBY_ID)
);

CREATE TABLE LOGHISTORY
(
  LOG_ID      TEXT NOT NULL,
  LOGIN TIME  TEXT NULL    ,
  LOGOUT TIME TEXT NULL    ,
  ID_EMAIL    TEXT NOT NULL,
  PRIMARY KEY (LOG_ID),
CONSTRAINT FK_MEMBER_TO_LOGHISTORY
    FOREIGN KEY (ID_EMAIL)
    REFERENCES MEMBER (ID_EMAIL)
);


CREATE TABLE PROJECT
(
  PRJ_ID   FLOAT NOT NULL,
  PRJ_NAME TEXT  NULL    ,
  THEME    TEXT  NULL    ,
  RANK     FLOAT NULL    ,
  DUE_DATE FLOAT NULL    ,
  PRIMARY KEY (PRJ_ID)
);

CREATE TABLE TEACHER
(
  TEACHER_ID TEXT  NOT NULL,
  NAME       TEXT  NULL    ,
  BIRTHDATE  FLOAT NULL    ,
  ROLL_NO    FLOAT NULL    ,
  ORG_ID     FLOAT NOT NULL,
  PRJ_ID     FLOAT NOT NULL,
  AUTH_ID    FLOAT NOT NULL,
  PRIMARY KEY (TEACHER_ID)
);



INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME) VALUES ('DEPT1', 'IT Billing');
INSERT INTO ORGANIZATION (ORG_ID, ORG_NAME) VALUES ('DEPT2', 'Engineering');

INSERT INTO MEMBER (ID_EMAIL, NAME, ORG_ID) VALUES ('paul01@gmail.com', 'Paul', 'DEPT1');
INSERT INTO MEMBER (ID_EMAIL, NAME, ORG_ID) VALUES ('texas@imfblog.org', 'Allen', 'DEPT2');
INSERT INTO MEMBER (ID_EMAIL, NAME, ORG_ID) VALUES ('norway@iotm.com', 'Teddy', 'DEPT1');

INSERT INTO AUTHORITY (AUTH_ID, AUTH_NAME) VALUES ('AUTH1', 'MANAGER');
INSERT INTO AUTHORITY (AUTH_ID, AUTH_NAME) VALUES ('AUTH2', 'ADMIN');
INSERT INTO AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('AUTH3', 'GUEST');



INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('paul01@gmail.com', 'AUTH1');
INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('paul01@gmail.com', 'AUTH2');
INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('paul01@gmail.com', 'AUTH3');
INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('texas@imfblog.org', 'AUTH2');
INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('texas@imfblog.org', 'AUTH3');
INSERT INTO MEMBER_AUTHORITY (ID_EMAIL, AUTH_ID) VALUES ('norway@iotm.com', 'AUTH2');

