-- SQLite
CREATE TABLE AUTH_MEM
(
  AUTH_ID TEXT NOT NULL,
  MEM_SEQ TEXT NOT NULL,

  CONSTRAINT FK_AUTHORITY_TO_AUTH_MEM
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTHORITY (AUTH_ID),
    CONSTRAINT FK_MEMBERS_TO_AUTH_MEM
    FOREIGN KEY (MEM_SEQ)
    REFERENCES MEMBERS (MEM_SEQ)
);

CREATE TABLE AUTHORITY
(
  AUTH_ID  TEXT NOT NULL,
  NAME     TEXT NULL    ,
  DESCR    TEXT NULL    ,
  USE_YN   TEXT NULL    ,
  REG_SEQ  TEXT NULL    ,
  REG_DATE INT  NULL    ,
  MOD_SEQ  TEXT NULL    ,
  MOD_DATE INT  NULL    ,
  PRIMARY KEY (AUTH_ID)
);

CREATE TABLE MEMBERS
(
  MEM_SEQ  TEXT NOT NULL,
  ID       INT  NULL,
  NAME     TEXT NULL    ,
  EMAIL    TEXT NULL    ,
  PHONE    INT  NULL    ,
  REG_SEQ  TEXT NULL    ,
  REG_DATE INT  NULL    ,
  MOD_SEQ  TEXT NULL    ,
  MOD_DATE INT  NULL    ,
  ORG_SEQ  TEXT NOT NULL,
  PRIMARY KEY (MEM_SEQ),

  CONSTRAINT FK_ORGANIZATION_TO_MEMBERS
    FOREIGN KEY (ORG_SEQ)
    REFERENCES ORGANIZATION (ORG_SEQ)
);

CREATE TABLE ORGANIZATION
(
  ORG_SEQ   TEXT NOT NULL,
  ORG_NAME  TEXT NULL    ,
  TELEPHONE INT  NULL    ,
  ORG_ORDER     INT  NULL    ,
  PRIMARY KEY (ORG_SEQ)
);



INSERT INTO MEMBERS(MEM_SEQ, ID, NAME, EMAIL, ORG_SEQ) VALUES ('MEM_01', 1, 'PAUL', 'paul01@gmail.com', 'IT');
INSERT INTO MEMBERS(MEM_SEQ, ID, NAME, EMAIL, ORG_SEQ) VALUES ('MEM_02', 2, 'ALLEN', 'texas@imfblog.org', 'ENGN');
INSERT INTO MEMBERS(MEM_SEQ, ID, NAME, EMAIL, ORG_SEQ) VALUES ('MEM_03', 3, 'TEDDY', 'norway@iotm.com', 'It');

INSERT INTO ORGANIZATION(ORG_SEQ, ORG_NAME) VALUES ('IT', 'IT BILLING');
INSERT INTO ORGANIZATION(ORG_SEQ, ORG_NAME) VALUES ('ENGN', 'ENGINEERING');

INSERT INTO AUTHORITY(AUTH_ID, NAME) VALUES ('GUE', 'GUEST');
INSERT INTO AUTHORITY(AUTH_ID, NAME) VALUES ('ADM', 'ADMIN');
INSERT INTO AUTHORITY(AUTH_ID, NAME) VALUES ('MAN', 'MANAGER');

