-- SQLite
CREATE TABLE ATTACHFILES
(
  FILE_NAME   TEXT NULL    ,
  FILE_HIGHT  REAL NULL    ,
  FILE_WIDTH  REAL NULL    ,
  FILE_URL    TEXT NULL    ,
  UPLOAD_TIME REAL NULL    ,
  FILE_ID     TEXT NOT NULL,
  ID_Email    TEXT NOT NULL,
  B_ID        TEXT NULL,
  PRIMARY KEY (FILE_ID),
CONSTRAINT FK_MEMBER_TO_ATTACHFILES
    FOREIGN KEY (ID_Email)
    REFERENCES MEMBER (ID_Email),
CONSTRAINT FK_MULTI_BOARD_TO_ATTACHFILES
    FOREIGN KEY (B_ID)
    REFERENCES MULTI_BOARD (B_ID)
);

CREATE TABLE AUTHORITY
(
  AUTH_CODE   TEXT NOT NULL,
  NAME        TEXT NULL    ,
  GRANT_DATE  TEXT NULL    ,
  EXPIRE_DATE TEXT NULL    ,
  ORG_CODE    REAL NULL    ,
  PRIMARY KEY (AUTH_CODE)
);

CREATE TABLE HOBBY
(
  H_CODE TEXT NOT NULL,
  NAME   TEXT NULL    ,
  PRIMARY KEY (H_CODE)
);

CREATE TABLE LOGHISTORY
(
  LOGIN TIME  REAL NULL    ,
  LOGOUT TIME REAL NULL    ,
  ACTION      TEXT NULL    ,
  LOG_CODE    TEXT NOT NULL,
  ID_Email    TEXT NOT NULL,
  PRIMARY KEY (LOG_CODE),
CONSTRAINT FK_MEMBER_TO_LOGHISTORY
    FOREIGN KEY (ID_Email)
    REFERENCES MEMBER (ID_Email)
);

CREATE TABLE MEMBER
(
  ID_Email  TEXT NOT NULL,
  PASSWORD  TEXT NULL    ,
  NAME      TEXT NULL    ,
  AGE       REAL NULL    ,
  SEX       TEXT NULL    ,
  ORG_CODE  REAL NOT NULL,
  AUTH_CODE TEXT NOT NULL,
  PRIMARY KEY (ID_Email),
CONSTRAINT FK_ORGANIZATION_TO_MEMBER
    FOREIGN KEY (ORG_CODE)
    REFERENCES ORGANIZATION (ORG_CODE),
CONSTRAINT FK_AUTHORITY_TO_MEMBER
    FOREIGN KEY (AUTH_CODE)
    REFERENCES AUTHORITY (AUTH_CODE)
);

CREATE TABLE MEMBER_HOBBY
(
  H_CODE   TEXT NOT NULL,
  ID_Email TEXT NOT NULL,
CONSTRAINT FK_HOBBY_TO_MEMBER_HOBBY
    FOREIGN KEY (H_CODE)
    REFERENCES HOBBY (H_CODE),
CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
    FOREIGN KEY (ID_Email)
    REFERENCES MEMBER (ID_Email)
);

CREATE TABLE MULTI_BOARD
(
  M_NAME   TEXT NULL    ,
  CONTENT  TEXT NULL    ,
  B_ID     TEXT NOT NULL,
  ID_Email TEXT NOT NULL,
  PRIMARY KEY (B_ID),
CONSTRAINT FK_MEMBER_TO_MULTI_BOARD
    FOREIGN KEY (ID_Email)
    REFERENCES MEMBER (ID_Email)
);

CREATE TABLE ORGANIZATION
(
  ORG_NAME TEXT NULL    ,
  TEL      TEXT NULL    ,
  ORG_CODE REAL NOT NULL,
  PRIMARY KEY (ORG_CODE)
);

INSERT INTO MEMBER (ID_Email, NAME, ORG_CODE, AUTH_CODE) 
VALUES
('wnstjd117', 'Paul', 1, 'A'),
('T722', 'Teddy', 2, 'B'),
('P722', 'jun', 3, 'C');

INSERT INTO ATTACHFILES (FILE_ID, FILE_NAME, ID_Email)
VALUES
('F1', 'poster.png', 'wnstjd117'),
('F2', 'poster02.png', 'wnstjd117'),
('F3', 'poster03.png', 'P722'),
('A1', 'actor.png', 'P722'),
('A2', 'actot02.png', 'T722'),
('A3', 'actor03.png', 'T722');


INSERT INTO MULTI_BOARD (M_NAME, CONTENT, B_ID, ID_Email)
VALUES ('용감한 가족', '한국 영화 장르', 'con1e', 'wnstjd117');


SELECT*FROM MULTI_BOARD;
