-- SQLite
-- SELECT STORE_ID, STORE_NAME, OWNER, TEL, ADDRESS, 
-- PROVINCE_ID, OPR_TIME, PERSONELL_ID, PARTICIPATE_ID, 
-- MENTYPE_ID, DONATION_ID
-- FROM `GOOD_STORE`;

--LOCATION
    
--이너조인으로 큰틀에 계속 교집합하면 쉽게 할 수 있고 레프트조인으로도 가능은 하다.


SELECT STORE_ID, STORE_NAME, OWNER, TEL, ADDRESS,T4.PROVINCE_NAME,OPR_TIME, T4.AMOUNT_OF_PERSONELL, 
T4.PATICIPATION,BENEFIT_MENU.MENU_TYPE, T4.DONATION_AMOUNT
FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT* FROM (SELECT * FROM GOOD_STORE) AS GS 
                        LEFT OUTER JOIN LOCATION ON GS.PROVINCE_ID = LOCATION.PROVINCE_ID) AS T1
                    LEFT OUTER JOIN DONATION_GENERAL ON T1.PARTICIPATE_ID = DONATION_GENERAL.PARTICIPATE_ID) AS T2
                LEFT OUTER JOIN ROUTINAL_DONATION ON T2.DONATION_ID = ROUTINAL_DONATION.DONATION_ID) AS T3
            LEFT OUTER JOIN BENEFIT_PERSONELL ON T3.PERSONELL_ID = BENEFIT_PERSONELL.PERSONELL_ID) AS T4
        LEFT OUTER JOIN BENEFIT_MENU ON T4.MENTYPE_ID = BENEFIT_MENU.MENTYPE_ID;



DROP TABLE GOOD_STORE_fdk;
--테이블 복제

CREATE TABLE GOOD_STORE_fdk(
    STORE_ID REAL NOT NULL, 
    STORE_NAME TEXT NULL, 
    OWNER TEXT NULL, 
    TEL TEXT NULL, 
    ADDRESS TEXT NULL,
    PROVINCE_NAME TEXT NULL,
    OPR_TIME TEXT NULL, 
    AMOUNT_OF_PERSONELL TEXT NULL, 
    PATICIPATION TEXT NULL,
    MENU_TYPE TEXT NULL, 
    DONATION_AMOUNT
);

--테이블값 인서트

INSERT INTO GOOD_STORE_fdk
SELECT STORE_ID, STORE_NAME, OWNER, TEL, ADDRESS,T4.PROVINCE_NAME,OPR_TIME, T4.AMOUNT_OF_PERSONELL, 
T4.PATICIPATION,BENEFIT_MENU.MENU_TYPE, T4.DONATION_AMOUNT
FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT* FROM (SELECT * FROM GOOD_STORE) AS GS 
                        LEFT OUTER JOIN LOCATION ON GS.PROVINCE_ID = LOCATION.PROVINCE_ID) AS T1
                    LEFT OUTER JOIN DONATION_GENERAL ON T1.PARTICIPATE_ID = DONATION_GENERAL.PARTICIPATE_ID) AS T2
                LEFT OUTER JOIN ROUTINAL_DONATION ON T2.DONATION_ID = ROUTINAL_DONATION.DONATION_ID) AS T3
            LEFT OUTER JOIN BENEFIT_PERSONELL ON T3.PERSONELL_ID = BENEFIT_PERSONELL.PERSONELL_ID) AS T4
        LEFT OUTER JOIN BENEFIT_MENU ON T4.MENTYPE_ID = BENEFIT_MENU.MENTYPE_ID;


SELECT count(STORE_ID)
FROM GOOD_STORE_fdk;

