-- SQLite

SELECT GOOD_STORE.OWNER, GOOD_STORE.STORE_NAME, LOCATION.PROVINCE_NAME, DONATION_GENERAL.PATICIPATION,
GOOD_STORE.TEL, GOOD_STORE.ADDRESS, GOOD_STORE.OPR_TIME, BENEFIT_PERSONELL.AMOUNT_OF_PERSONELL,
BENEFIT_MENU.MENU_TYPE, ROUTINAL_DONATION.DONATION_AMOUNT
FROM GOOD_STORE

LEFT OUTER JOIN LOCATION
ON GOOD_STORE.PROVINCE_ID = LOCATION.PROVINCE_ID

LEFT OUTER JOIN BENEFIT_PERSONELL
ON GOOD_STORE.PERSONELL_ID = BENEFIT_PERSONELL.PERSONELL_ID

LEFT OUTER JOIN DONATION_GENERAL
ON GOOD_STORE.PARTICIPATE_ID = DONATION_GENERAL.PARTICIPATE_ID

LEFT OUTER JOIN ROUTINAL_DONATION
ON GOOD_STORE.DONATION_ID = ROUTINAL_DONATION.DONATION_ID

LEFT OUTER JOIN BENEFIT_MENU
ON GOOD_STORE.MENTYPE_ID = BENEFIT_MENU.MENTYPE_ID;