-- SQLite
Select STORE_NAME, OWNER, PROVINCE_NAME, OPR_TIME, PATICIPATION, DONATION_AMOUNT, MENU_TYPE, AMOUNT_OF_PERSONELL
from GOOD_STORE 
inner join LOCATION on LOCATION.PROVINCE_ID=GOOD_STORE.PROVINCE_ID
 inner join DONATION_GENERAL on DONATION_GENERAL.PARTICIPATE_ID = GOOD_STORE.PARTICIPATE_ID
   inner join ROUTINAL_DONATION on GOOD_STORE.DONATION_ID = ROUTINAL_DONATION.DONATION_ID
     inner join BENEFIT_MENU on BENEFIT_MENU.MENTYPE_ID = GOOD_STORE.MENTYPE_ID
       inner join BENEFIT_PERSONELL on BENEFIT_PERSONELL.PERSONELL_ID = GOOD_STORE.PERSONELL_ID;


select count(*) from temp_dump_excel_table;





