-- SQLite

SELECT LOCATION.PROVINCE_NAME AS LOCATION, goodinf_table.상호명 AS STORE_NAME, ROUTINAL_DONATION.DONATION_AMOUNT AS DONATION_AMOUNT, DONATION_GENERAL.PATICIPATION AS DONATION,
BENEFIT_PERSONELL.AMOUNT_OF_PERSONELL AS NUMBER_OF_BENEFICIARIES, BENEFIT_MENU.MENU_TYPE AS MENU_PROVIDED
FROM goodinf_table
LEFT JOIN LOCATION ON LOCATION.PROVINCE_NAME=goodinf_table.지역
LEFT JOIN ROUTINAL_DONATION ON ROUTINAL_DONATION.DONATION_AMOUNT=goodinf_table.월정기후원
LEFT JOIN DONATION_GENERAL ON DONATION_GENERAL.PATICIPATION=goodinf_table.후원회원참여여부
LEFT JOIN BENEFIT_PERSONELL ON BENEFIT_PERSONELL.AMOUNT_OF_PERSONELL=goodinf_table.제공대상1
LEFT JOIN BENEFIT_MENU ON BENEFIT_MENU.MENU_TYPE=goodinf_table.제공품목_전메뉴or일부한정상품등;

CREATE TABLE joined_good( LOCATION TEXT NULL,
STORE_NAME TEXT NULL,
DONATION_AMOUNT FLOAT NULL,
DONATION TEXT NULL,
NUMBER_OF_BENEFICIARIES TEXT NULL,
MENU_PROVIDED TEXT NULL);

INSERT INTO joined_good (LOCATION, STORE_NAME, DONATION_AMOUNT, DONATION,NUMBER_OF_BENEFICIARIES, MENU_PROVIDED
)
SELECT goodinf_table.지역 , goodinf_table.상호명 , goodinf_table.월정기후원, goodinf_table.후원회원참여여부,
goodinf_table.제공대상1, goodinf_table.제공품목_전메뉴or일부한정상품등
FROM goodinf_table;

SELECT COUNT(상호명) as COUNT FROM goodinf_table;
SELECT COUNT(STORE_NAME) as COUNT FROM joined_good;