# -*- coding: utf-8 -*-
"""20200506_goodinfluence_LeeJunO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sROVsh0DsVOTQDKJAGa5O4CPnkvJOfkR
"""

import requests
from bs4 import BeautifulSoup
import json
import pandas as pd
import numpy as np
import os

!pip install sqlalchemy

cd ./drive

cd ./My Drive

ex = pd.read_excel('./선한영향력 동행 리스트(외부).xlsx',header=1)



ex.columns

ex

del ex['순번']

ex

ex2 = pd.Series(ex['제공대상2'])

ex2, type(ex2)

str(ex2).strip()

temp1=[]
temp2=[]
temp3=[]
temp4=[]
parser=[]

for i in range(len(ex2)): 
  parser = str(ex2[i]).split(',')
  for j in range(len(parser)):    
    if j ==0:  temp1 +=[parser[0]]
    elif j ==1:  temp2 +=[parser[1]]      
    elif j ==2:  temp3 +=[parser[2]]      
    elif j ==3:  temp4 +=[parser[3]]

temp1

for i in range(len(temp1)):
  if temp1[i]=='nan':
    temp1[i]=None
  else:
    continue

temp1,len(temp1)

temp2

temp3

temp4

temp1= pd.DataFrame(temp1)
temp2= pd.DataFrame(temp2)
temp3=pd.DataFrame(temp3)
temp4=pd.DataFrame(temp4)

temps = pd.concat([temp1,temp2,temp3,temp4],axis=1)

temps.columns=['제공대상2_1','제공대상2_2','제공대상2_3','제공대상2_4']

temps

good=pd.concat([ex,temps],axis=1)

good.columns

good.columns=['지역', '진함', '상호명', '사업장연락처', '사업장주소','영업시간', '제공품목', '제공대상1', '제공대상2','후원회원참여여부', '월정기후원', '제공대상2_1', '제공대상2_2', '제공대상2_3', '제공대상2_4']

good

type(good)

import sqlite3
conn = sqlite3.connect('goodinfluence_20200506.db')
good.to_sql('goodinfluence_table',conn,if_exists='replace')

temps2 = pd.concat([temp1,temp2,temp3,temp4],axis=0)

temps2.columns = ['target']

temps2

temps2.to_sql('target_table',conn,if_exists='replace')